; ===================================================================
; INVADERS_DATA.ASM - Pre-shifted sprites and authentic ROM tables
; Generated by build_invaders_assets.py
; ===================================================================

; HGR Scanline Base Addresses (0..191) for Page 1
hgr_lo:
    .byte <$2000 ; Y=0
    .byte <$2400 ; Y=1
    .byte <$2800 ; Y=2
    .byte <$2C00 ; Y=3
    .byte <$3000 ; Y=4
    .byte <$3400 ; Y=5
    .byte <$3800 ; Y=6
    .byte <$3C00 ; Y=7
    .byte <$2080 ; Y=8
    .byte <$2480 ; Y=9
    .byte <$2880 ; Y=10
    .byte <$2C80 ; Y=11
    .byte <$3080 ; Y=12
    .byte <$3480 ; Y=13
    .byte <$3880 ; Y=14
    .byte <$3C80 ; Y=15
    .byte <$2100 ; Y=16
    .byte <$2500 ; Y=17
    .byte <$2900 ; Y=18
    .byte <$2D00 ; Y=19
    .byte <$3100 ; Y=20
    .byte <$3500 ; Y=21
    .byte <$3900 ; Y=22
    .byte <$3D00 ; Y=23
    .byte <$2180 ; Y=24
    .byte <$2580 ; Y=25
    .byte <$2980 ; Y=26
    .byte <$2D80 ; Y=27
    .byte <$3180 ; Y=28
    .byte <$3580 ; Y=29
    .byte <$3980 ; Y=30
    .byte <$3D80 ; Y=31
    .byte <$2200 ; Y=32
    .byte <$2600 ; Y=33
    .byte <$2A00 ; Y=34
    .byte <$2E00 ; Y=35
    .byte <$3200 ; Y=36
    .byte <$3600 ; Y=37
    .byte <$3A00 ; Y=38
    .byte <$3E00 ; Y=39
    .byte <$2280 ; Y=40
    .byte <$2680 ; Y=41
    .byte <$2A80 ; Y=42
    .byte <$2E80 ; Y=43
    .byte <$3280 ; Y=44
    .byte <$3680 ; Y=45
    .byte <$3A80 ; Y=46
    .byte <$3E80 ; Y=47
    .byte <$2300 ; Y=48
    .byte <$2700 ; Y=49
    .byte <$2B00 ; Y=50
    .byte <$2F00 ; Y=51
    .byte <$3300 ; Y=52
    .byte <$3700 ; Y=53
    .byte <$3B00 ; Y=54
    .byte <$3F00 ; Y=55
    .byte <$2380 ; Y=56
    .byte <$2780 ; Y=57
    .byte <$2B80 ; Y=58
    .byte <$2F80 ; Y=59
    .byte <$3380 ; Y=60
    .byte <$3780 ; Y=61
    .byte <$3B80 ; Y=62
    .byte <$3F80 ; Y=63
    .byte <$2028 ; Y=64
    .byte <$2428 ; Y=65
    .byte <$2828 ; Y=66
    .byte <$2C28 ; Y=67
    .byte <$3028 ; Y=68
    .byte <$3428 ; Y=69
    .byte <$3828 ; Y=70
    .byte <$3C28 ; Y=71
    .byte <$20A8 ; Y=72
    .byte <$24A8 ; Y=73
    .byte <$28A8 ; Y=74
    .byte <$2CA8 ; Y=75
    .byte <$30A8 ; Y=76
    .byte <$34A8 ; Y=77
    .byte <$38A8 ; Y=78
    .byte <$3CA8 ; Y=79
    .byte <$2128 ; Y=80
    .byte <$2528 ; Y=81
    .byte <$2928 ; Y=82
    .byte <$2D28 ; Y=83
    .byte <$3128 ; Y=84
    .byte <$3528 ; Y=85
    .byte <$3928 ; Y=86
    .byte <$3D28 ; Y=87
    .byte <$21A8 ; Y=88
    .byte <$25A8 ; Y=89
    .byte <$29A8 ; Y=90
    .byte <$2DA8 ; Y=91
    .byte <$31A8 ; Y=92
    .byte <$35A8 ; Y=93
    .byte <$39A8 ; Y=94
    .byte <$3DA8 ; Y=95
    .byte <$2228 ; Y=96
    .byte <$2628 ; Y=97
    .byte <$2A28 ; Y=98
    .byte <$2E28 ; Y=99
    .byte <$3228 ; Y=100
    .byte <$3628 ; Y=101
    .byte <$3A28 ; Y=102
    .byte <$3E28 ; Y=103
    .byte <$22A8 ; Y=104
    .byte <$26A8 ; Y=105
    .byte <$2AA8 ; Y=106
    .byte <$2EA8 ; Y=107
    .byte <$32A8 ; Y=108
    .byte <$36A8 ; Y=109
    .byte <$3AA8 ; Y=110
    .byte <$3EA8 ; Y=111
    .byte <$2328 ; Y=112
    .byte <$2728 ; Y=113
    .byte <$2B28 ; Y=114
    .byte <$2F28 ; Y=115
    .byte <$3328 ; Y=116
    .byte <$3728 ; Y=117
    .byte <$3B28 ; Y=118
    .byte <$3F28 ; Y=119
    .byte <$23A8 ; Y=120
    .byte <$27A8 ; Y=121
    .byte <$2BA8 ; Y=122
    .byte <$2FA8 ; Y=123
    .byte <$33A8 ; Y=124
    .byte <$37A8 ; Y=125
    .byte <$3BA8 ; Y=126
    .byte <$3FA8 ; Y=127
    .byte <$2050 ; Y=128
    .byte <$2450 ; Y=129
    .byte <$2850 ; Y=130
    .byte <$2C50 ; Y=131
    .byte <$3050 ; Y=132
    .byte <$3450 ; Y=133
    .byte <$3850 ; Y=134
    .byte <$3C50 ; Y=135
    .byte <$20D0 ; Y=136
    .byte <$24D0 ; Y=137
    .byte <$28D0 ; Y=138
    .byte <$2CD0 ; Y=139
    .byte <$30D0 ; Y=140
    .byte <$34D0 ; Y=141
    .byte <$38D0 ; Y=142
    .byte <$3CD0 ; Y=143
    .byte <$2150 ; Y=144
    .byte <$2550 ; Y=145
    .byte <$2950 ; Y=146
    .byte <$2D50 ; Y=147
    .byte <$3150 ; Y=148
    .byte <$3550 ; Y=149
    .byte <$3950 ; Y=150
    .byte <$3D50 ; Y=151
    .byte <$21D0 ; Y=152
    .byte <$25D0 ; Y=153
    .byte <$29D0 ; Y=154
    .byte <$2DD0 ; Y=155
    .byte <$31D0 ; Y=156
    .byte <$35D0 ; Y=157
    .byte <$39D0 ; Y=158
    .byte <$3DD0 ; Y=159
    .byte <$2250 ; Y=160
    .byte <$2650 ; Y=161
    .byte <$2A50 ; Y=162
    .byte <$2E50 ; Y=163
    .byte <$3250 ; Y=164
    .byte <$3650 ; Y=165
    .byte <$3A50 ; Y=166
    .byte <$3E50 ; Y=167
    .byte <$22D0 ; Y=168
    .byte <$26D0 ; Y=169
    .byte <$2AD0 ; Y=170
    .byte <$2ED0 ; Y=171
    .byte <$32D0 ; Y=172
    .byte <$36D0 ; Y=173
    .byte <$3AD0 ; Y=174
    .byte <$3ED0 ; Y=175
    .byte <$2350 ; Y=176
    .byte <$2750 ; Y=177
    .byte <$2B50 ; Y=178
    .byte <$2F50 ; Y=179
    .byte <$3350 ; Y=180
    .byte <$3750 ; Y=181
    .byte <$3B50 ; Y=182
    .byte <$3F50 ; Y=183
    .byte <$23D0 ; Y=184
    .byte <$27D0 ; Y=185
    .byte <$2BD0 ; Y=186
    .byte <$2FD0 ; Y=187
    .byte <$33D0 ; Y=188
    .byte <$37D0 ; Y=189
    .byte <$3BD0 ; Y=190
    .byte <$3FD0 ; Y=191

hgr_hi:
    .byte >$2000 ; Y=0
    .byte >$2400 ; Y=1
    .byte >$2800 ; Y=2
    .byte >$2C00 ; Y=3
    .byte >$3000 ; Y=4
    .byte >$3400 ; Y=5
    .byte >$3800 ; Y=6
    .byte >$3C00 ; Y=7
    .byte >$2080 ; Y=8
    .byte >$2480 ; Y=9
    .byte >$2880 ; Y=10
    .byte >$2C80 ; Y=11
    .byte >$3080 ; Y=12
    .byte >$3480 ; Y=13
    .byte >$3880 ; Y=14
    .byte >$3C80 ; Y=15
    .byte >$2100 ; Y=16
    .byte >$2500 ; Y=17
    .byte >$2900 ; Y=18
    .byte >$2D00 ; Y=19
    .byte >$3100 ; Y=20
    .byte >$3500 ; Y=21
    .byte >$3900 ; Y=22
    .byte >$3D00 ; Y=23
    .byte >$2180 ; Y=24
    .byte >$2580 ; Y=25
    .byte >$2980 ; Y=26
    .byte >$2D80 ; Y=27
    .byte >$3180 ; Y=28
    .byte >$3580 ; Y=29
    .byte >$3980 ; Y=30
    .byte >$3D80 ; Y=31
    .byte >$2200 ; Y=32
    .byte >$2600 ; Y=33
    .byte >$2A00 ; Y=34
    .byte >$2E00 ; Y=35
    .byte >$3200 ; Y=36
    .byte >$3600 ; Y=37
    .byte >$3A00 ; Y=38
    .byte >$3E00 ; Y=39
    .byte >$2280 ; Y=40
    .byte >$2680 ; Y=41
    .byte >$2A80 ; Y=42
    .byte >$2E80 ; Y=43
    .byte >$3280 ; Y=44
    .byte >$3680 ; Y=45
    .byte >$3A80 ; Y=46
    .byte >$3E80 ; Y=47
    .byte >$2300 ; Y=48
    .byte >$2700 ; Y=49
    .byte >$2B00 ; Y=50
    .byte >$2F00 ; Y=51
    .byte >$3300 ; Y=52
    .byte >$3700 ; Y=53
    .byte >$3B00 ; Y=54
    .byte >$3F00 ; Y=55
    .byte >$2380 ; Y=56
    .byte >$2780 ; Y=57
    .byte >$2B80 ; Y=58
    .byte >$2F80 ; Y=59
    .byte >$3380 ; Y=60
    .byte >$3780 ; Y=61
    .byte >$3B80 ; Y=62
    .byte >$3F80 ; Y=63
    .byte >$2028 ; Y=64
    .byte >$2428 ; Y=65
    .byte >$2828 ; Y=66
    .byte >$2C28 ; Y=67
    .byte >$3028 ; Y=68
    .byte >$3428 ; Y=69
    .byte >$3828 ; Y=70
    .byte >$3C28 ; Y=71
    .byte >$20A8 ; Y=72
    .byte >$24A8 ; Y=73
    .byte >$28A8 ; Y=74
    .byte >$2CA8 ; Y=75
    .byte >$30A8 ; Y=76
    .byte >$34A8 ; Y=77
    .byte >$38A8 ; Y=78
    .byte >$3CA8 ; Y=79
    .byte >$2128 ; Y=80
    .byte >$2528 ; Y=81
    .byte >$2928 ; Y=82
    .byte >$2D28 ; Y=83
    .byte >$3128 ; Y=84
    .byte >$3528 ; Y=85
    .byte >$3928 ; Y=86
    .byte >$3D28 ; Y=87
    .byte >$21A8 ; Y=88
    .byte >$25A8 ; Y=89
    .byte >$29A8 ; Y=90
    .byte >$2DA8 ; Y=91
    .byte >$31A8 ; Y=92
    .byte >$35A8 ; Y=93
    .byte >$39A8 ; Y=94
    .byte >$3DA8 ; Y=95
    .byte >$2228 ; Y=96
    .byte >$2628 ; Y=97
    .byte >$2A28 ; Y=98
    .byte >$2E28 ; Y=99
    .byte >$3228 ; Y=100
    .byte >$3628 ; Y=101
    .byte >$3A28 ; Y=102
    .byte >$3E28 ; Y=103
    .byte >$22A8 ; Y=104
    .byte >$26A8 ; Y=105
    .byte >$2AA8 ; Y=106
    .byte >$2EA8 ; Y=107
    .byte >$32A8 ; Y=108
    .byte >$36A8 ; Y=109
    .byte >$3AA8 ; Y=110
    .byte >$3EA8 ; Y=111
    .byte >$2328 ; Y=112
    .byte >$2728 ; Y=113
    .byte >$2B28 ; Y=114
    .byte >$2F28 ; Y=115
    .byte >$3328 ; Y=116
    .byte >$3728 ; Y=117
    .byte >$3B28 ; Y=118
    .byte >$3F28 ; Y=119
    .byte >$23A8 ; Y=120
    .byte >$27A8 ; Y=121
    .byte >$2BA8 ; Y=122
    .byte >$2FA8 ; Y=123
    .byte >$33A8 ; Y=124
    .byte >$37A8 ; Y=125
    .byte >$3BA8 ; Y=126
    .byte >$3FA8 ; Y=127
    .byte >$2050 ; Y=128
    .byte >$2450 ; Y=129
    .byte >$2850 ; Y=130
    .byte >$2C50 ; Y=131
    .byte >$3050 ; Y=132
    .byte >$3450 ; Y=133
    .byte >$3850 ; Y=134
    .byte >$3C50 ; Y=135
    .byte >$20D0 ; Y=136
    .byte >$24D0 ; Y=137
    .byte >$28D0 ; Y=138
    .byte >$2CD0 ; Y=139
    .byte >$30D0 ; Y=140
    .byte >$34D0 ; Y=141
    .byte >$38D0 ; Y=142
    .byte >$3CD0 ; Y=143
    .byte >$2150 ; Y=144
    .byte >$2550 ; Y=145
    .byte >$2950 ; Y=146
    .byte >$2D50 ; Y=147
    .byte >$3150 ; Y=148
    .byte >$3550 ; Y=149
    .byte >$3950 ; Y=150
    .byte >$3D50 ; Y=151
    .byte >$21D0 ; Y=152
    .byte >$25D0 ; Y=153
    .byte >$29D0 ; Y=154
    .byte >$2DD0 ; Y=155
    .byte >$31D0 ; Y=156
    .byte >$35D0 ; Y=157
    .byte >$39D0 ; Y=158
    .byte >$3DD0 ; Y=159
    .byte >$2250 ; Y=160
    .byte >$2650 ; Y=161
    .byte >$2A50 ; Y=162
    .byte >$2E50 ; Y=163
    .byte >$3250 ; Y=164
    .byte >$3650 ; Y=165
    .byte >$3A50 ; Y=166
    .byte >$3E50 ; Y=167
    .byte >$22D0 ; Y=168
    .byte >$26D0 ; Y=169
    .byte >$2AD0 ; Y=170
    .byte >$2ED0 ; Y=171
    .byte >$32D0 ; Y=172
    .byte >$36D0 ; Y=173
    .byte >$3AD0 ; Y=174
    .byte >$3ED0 ; Y=175
    .byte >$2350 ; Y=176
    .byte >$2750 ; Y=177
    .byte >$2B50 ; Y=178
    .byte >$2F50 ; Y=179
    .byte >$3350 ; Y=180
    .byte >$3750 ; Y=181
    .byte >$3B50 ; Y=182
    .byte >$3F50 ; Y=183
    .byte >$23D0 ; Y=184
    .byte >$27D0 ; Y=185
    .byte >$2BD0 ; Y=186
    .byte >$2FD0 ; Y=187
    .byte >$33D0 ; Y=188
    .byte >$37D0 ; Y=189
    .byte >$3BD0 ; Y=190
    .byte >$3FD0 ; Y=191

; Sprite: squid_f0 (8 lines x 3 bytes x 7 shifts)
spr_squid_f0:
; Shift 0
    .byte $00, $03, $00
    .byte $40, $07, $00
    .byte $60, $0F, $00
    .byte $30, $1B, $00
    .byte $70, $1F, $00
    .byte $20, $0B, $00
    .byte $10, $10, $00
    .byte $20, $08, $00
; Shift 1
    .byte $00, $06, $00
    .byte $00, $0F, $00
    .byte $40, $1F, $00
    .byte $60, $36, $00
    .byte $60, $3F, $00
    .byte $40, $16, $00
    .byte $20, $20, $00
    .byte $40, $10, $00
; Shift 2
    .byte $00, $0C, $00
    .byte $00, $1E, $00
    .byte $00, $3F, $00
    .byte $40, $6D, $00
    .byte $40, $7F, $00
    .byte $00, $2D, $00
    .byte $40, $40, $00
    .byte $00, $21, $00
; Shift 3
    .byte $00, $18, $00
    .byte $00, $3C, $00
    .byte $00, $7E, $00
    .byte $00, $5B, $01
    .byte $00, $7F, $01
    .byte $00, $5A, $00
    .byte $00, $01, $01
    .byte $00, $42, $00
; Shift 4
    .byte $00, $30, $00
    .byte $00, $78, $00
    .byte $00, $7C, $01
    .byte $00, $36, $03
    .byte $00, $7E, $03
    .byte $00, $34, $01
    .byte $00, $02, $02
    .byte $00, $04, $01
; Shift 5
    .byte $00, $60, $00
    .byte $00, $70, $01
    .byte $00, $78, $03
    .byte $00, $6C, $06
    .byte $00, $7C, $07
    .byte $00, $68, $02
    .byte $00, $04, $04
    .byte $00, $08, $02
; Shift 6
    .byte $00, $40, $01
    .byte $00, $60, $03
    .byte $00, $70, $07
    .byte $00, $58, $0D
    .byte $00, $78, $0F
    .byte $00, $50, $05
    .byte $00, $08, $08
    .byte $00, $10, $04

; Sprite: squid_f1 (8 lines x 3 bytes x 7 shifts)
spr_squid_f1:
; Shift 0
    .byte $00, $03, $00
    .byte $40, $07, $00
    .byte $60, $0F, $00
    .byte $30, $1B, $00
    .byte $70, $1F, $00
    .byte $40, $04, $00
    .byte $20, $0B, $00
    .byte $50, $14, $00
; Shift 1
    .byte $00, $06, $00
    .byte $00, $0F, $00
    .byte $40, $1F, $00
    .byte $60, $36, $00
    .byte $60, $3F, $00
    .byte $00, $09, $00
    .byte $40, $16, $00
    .byte $20, $29, $00
; Shift 2
    .byte $00, $0C, $00
    .byte $00, $1E, $00
    .byte $00, $3F, $00
    .byte $40, $6D, $00
    .byte $40, $7F, $00
    .byte $00, $12, $00
    .byte $00, $2D, $00
    .byte $40, $52, $00
; Shift 3
    .byte $00, $18, $00
    .byte $00, $3C, $00
    .byte $00, $7E, $00
    .byte $00, $5B, $01
    .byte $00, $7F, $01
    .byte $00, $24, $00
    .byte $00, $5A, $00
    .byte $00, $25, $01
; Shift 4
    .byte $00, $30, $00
    .byte $00, $78, $00
    .byte $00, $7C, $01
    .byte $00, $36, $03
    .byte $00, $7E, $03
    .byte $00, $48, $00
    .byte $00, $34, $01
    .byte $00, $4A, $02
; Shift 5
    .byte $00, $60, $00
    .byte $00, $70, $01
    .byte $00, $78, $03
    .byte $00, $6C, $06
    .byte $00, $7C, $07
    .byte $00, $10, $01
    .byte $00, $68, $02
    .byte $00, $14, $05
; Shift 6
    .byte $00, $40, $01
    .byte $00, $60, $03
    .byte $00, $70, $07
    .byte $00, $58, $0D
    .byte $00, $78, $0F
    .byte $00, $20, $02
    .byte $00, $50, $05
    .byte $00, $28, $0A

; Sprite: crab_f0 (8 lines x 3 bytes x 7 shifts)
spr_crab_f0:
; Shift 0
    .byte $20, $10, $00
    .byte $40, $08, $00
    .byte $60, $1F, $00
    .byte $30, $37, $00
    .byte $78, $7F, $00
    .byte $68, $5F, $00
    .byte $28, $50, $00
    .byte $40, $0D, $00
; Shift 1
    .byte $40, $20, $00
    .byte $00, $11, $00
    .byte $40, $3F, $00
    .byte $60, $6E, $00
    .byte $70, $7F, $01
    .byte $50, $3F, $01
    .byte $50, $20, $01
    .byte $00, $1B, $00
; Shift 2
    .byte $00, $41, $00
    .byte $00, $22, $00
    .byte $00, $7F, $00
    .byte $40, $5D, $01
    .byte $60, $7F, $03
    .byte $20, $7F, $02
    .byte $20, $41, $02
    .byte $00, $36, $00
; Shift 3
    .byte $00, $02, $01
    .byte $00, $44, $00
    .byte $00, $7E, $01
    .byte $00, $3B, $03
    .byte $40, $7F, $07
    .byte $40, $7E, $05
    .byte $40, $02, $05
    .byte $00, $6C, $00
; Shift 4
    .byte $00, $04, $02
    .byte $00, $08, $01
    .byte $00, $7C, $03
    .byte $00, $76, $06
    .byte $00, $7F, $0F
    .byte $00, $7D, $0B
    .byte $00, $05, $0A
    .byte $00, $58, $01
; Shift 5
    .byte $00, $08, $04
    .byte $00, $10, $02
    .byte $00, $78, $07
    .byte $00, $6C, $0D
    .byte $00, $7E, $1F
    .byte $00, $7A, $17
    .byte $00, $0A, $14
    .byte $00, $30, $03
; Shift 6
    .byte $00, $10, $08
    .byte $00, $20, $04
    .byte $00, $70, $0F
    .byte $00, $58, $1B
    .byte $00, $7C, $3F
    .byte $00, $74, $2F
    .byte $00, $14, $28
    .byte $00, $60, $06

; Sprite: crab_f1 (8 lines x 3 bytes x 7 shifts)
spr_crab_f1:
; Shift 0
    .byte $20, $10, $00
    .byte $48, $48, $00
    .byte $68, $5F, $00
    .byte $38, $77, $00
    .byte $78, $7F, $00
    .byte $70, $3F, $00
    .byte $20, $10, $00
    .byte $10, $20, $00
; Shift 1
    .byte $40, $20, $00
    .byte $10, $11, $01
    .byte $50, $3F, $01
    .byte $70, $6E, $01
    .byte $70, $7F, $01
    .byte $60, $7F, $00
    .byte $40, $20, $00
    .byte $20, $40, $00
; Shift 2
    .byte $00, $41, $00
    .byte $20, $22, $02
    .byte $20, $7F, $02
    .byte $60, $5D, $03
    .byte $60, $7F, $03
    .byte $40, $7F, $01
    .byte $00, $41, $00
    .byte $40, $00, $01
; Shift 3
    .byte $00, $02, $01
    .byte $40, $44, $04
    .byte $40, $7E, $05
    .byte $40, $3B, $07
    .byte $40, $7F, $07
    .byte $00, $7F, $03
    .byte $00, $02, $01
    .byte $00, $01, $02
; Shift 4
    .byte $00, $04, $02
    .byte $00, $09, $09
    .byte $00, $7D, $0B
    .byte $00, $77, $0E
    .byte $00, $7F, $0F
    .byte $00, $7E, $07
    .byte $00, $04, $02
    .byte $00, $02, $04
; Shift 5
    .byte $00, $08, $04
    .byte $00, $12, $12
    .byte $00, $7A, $17
    .byte $00, $6E, $1D
    .byte $00, $7E, $1F
    .byte $00, $7C, $0F
    .byte $00, $08, $04
    .byte $00, $04, $08
; Shift 6
    .byte $00, $10, $08
    .byte $00, $24, $24
    .byte $00, $74, $2F
    .byte $00, $5C, $3B
    .byte $00, $7C, $3F
    .byte $00, $78, $1F
    .byte $00, $10, $08
    .byte $00, $08, $10

; Sprite: octo_f0 (8 lines x 3 bytes x 7 shifts)
spr_octo_f0:
; Shift 0
    .byte $40, $07, $00
    .byte $78, $3F, $00
    .byte $7C, $7F, $00
    .byte $1C, $73, $00
    .byte $7C, $7F, $00
    .byte $60, $0C, $00
    .byte $30, $1B, $00
    .byte $0C, $60, $00
; Shift 1
    .byte $00, $0F, $00
    .byte $70, $7F, $00
    .byte $78, $7F, $01
    .byte $38, $66, $01
    .byte $78, $7F, $01
    .byte $40, $19, $00
    .byte $60, $36, $00
    .byte $18, $40, $01
; Shift 2
    .byte $00, $1E, $00
    .byte $60, $7F, $01
    .byte $70, $7F, $03
    .byte $70, $4C, $03
    .byte $70, $7F, $03
    .byte $00, $33, $00
    .byte $40, $6D, $00
    .byte $30, $00, $03
; Shift 3
    .byte $00, $3C, $00
    .byte $40, $7F, $03
    .byte $60, $7F, $07
    .byte $60, $19, $07
    .byte $60, $7F, $07
    .byte $00, $66, $00
    .byte $00, $5B, $01
    .byte $60, $00, $06
; Shift 4
    .byte $00, $78, $00
    .byte $00, $7F, $07
    .byte $40, $7F, $0F
    .byte $40, $33, $0E
    .byte $40, $7F, $0F
    .byte $00, $4C, $01
    .byte $00, $36, $03
    .byte $40, $01, $0C
; Shift 5
    .byte $00, $70, $01
    .byte $00, $7E, $0F
    .byte $00, $7F, $1F
    .byte $00, $67, $1C
    .byte $00, $7F, $1F
    .byte $00, $18, $03
    .byte $00, $6C, $06
    .byte $00, $03, $18
; Shift 6
    .byte $00, $60, $03
    .byte $00, $7C, $1F
    .byte $00, $7E, $3F
    .byte $00, $4E, $39
    .byte $00, $7E, $3F
    .byte $00, $30, $06
    .byte $00, $58, $0D
    .byte $00, $06, $30

; Sprite: octo_f1 (8 lines x 3 bytes x 7 shifts)
spr_octo_f1:
; Shift 0
    .byte $40, $07, $00
    .byte $78, $3F, $00
    .byte $7C, $7F, $00
    .byte $1C, $73, $00
    .byte $7C, $7F, $00
    .byte $70, $1C, $00
    .byte $18, $33, $00
    .byte $30, $18, $00
; Shift 1
    .byte $00, $0F, $00
    .byte $70, $7F, $00
    .byte $78, $7F, $01
    .byte $38, $66, $01
    .byte $78, $7F, $01
    .byte $60, $39, $00
    .byte $30, $66, $00
    .byte $60, $30, $00
; Shift 2
    .byte $00, $1E, $00
    .byte $60, $7F, $01
    .byte $70, $7F, $03
    .byte $70, $4C, $03
    .byte $70, $7F, $03
    .byte $40, $73, $00
    .byte $60, $4C, $01
    .byte $40, $61, $00
; Shift 3
    .byte $00, $3C, $00
    .byte $40, $7F, $03
    .byte $60, $7F, $07
    .byte $60, $19, $07
    .byte $60, $7F, $07
    .byte $00, $67, $01
    .byte $40, $19, $03
    .byte $00, $43, $01
; Shift 4
    .byte $00, $78, $00
    .byte $00, $7F, $07
    .byte $40, $7F, $0F
    .byte $40, $33, $0E
    .byte $40, $7F, $0F
    .byte $00, $4E, $03
    .byte $00, $33, $06
    .byte $00, $06, $03
; Shift 5
    .byte $00, $70, $01
    .byte $00, $7E, $0F
    .byte $00, $7F, $1F
    .byte $00, $67, $1C
    .byte $00, $7F, $1F
    .byte $00, $1C, $07
    .byte $00, $66, $0C
    .byte $00, $0C, $06
; Shift 6
    .byte $00, $60, $03
    .byte $00, $7C, $1F
    .byte $00, $7E, $3F
    .byte $00, $4E, $39
    .byte $00, $7E, $3F
    .byte $00, $38, $0E
    .byte $00, $4C, $19
    .byte $00, $18, $0C

; Sprite: alien_exp (8 lines x 3 bytes x 7 shifts)
spr_alien_exp:
; Shift 0
    .byte $20, $04, $00
    .byte $44, $22, $00
    .byte $08, $10, $00
    .byte $10, $08, $00
    .byte $06, $60, $00
    .byte $10, $08, $00
    .byte $48, $12, $00
    .byte $24, $24, $00
; Shift 1
    .byte $40, $08, $00
    .byte $08, $45, $00
    .byte $10, $20, $00
    .byte $20, $10, $00
    .byte $0C, $40, $01
    .byte $20, $10, $00
    .byte $10, $25, $00
    .byte $48, $48, $00
; Shift 2
    .byte $00, $11, $00
    .byte $10, $0A, $01
    .byte $20, $40, $00
    .byte $40, $20, $00
    .byte $18, $00, $03
    .byte $40, $20, $00
    .byte $20, $4A, $00
    .byte $10, $11, $01
; Shift 3
    .byte $00, $22, $00
    .byte $20, $14, $02
    .byte $40, $00, $01
    .byte $00, $41, $00
    .byte $30, $00, $06
    .byte $00, $41, $00
    .byte $40, $14, $01
    .byte $20, $22, $02
; Shift 4
    .byte $00, $44, $00
    .byte $40, $28, $04
    .byte $00, $01, $02
    .byte $00, $02, $01
    .byte $60, $00, $0C
    .byte $00, $02, $01
    .byte $00, $29, $02
    .byte $40, $44, $04
; Shift 5
    .byte $00, $08, $01
    .byte $00, $51, $08
    .byte $00, $02, $04
    .byte $00, $04, $02
    .byte $40, $01, $18
    .byte $00, $04, $02
    .byte $00, $52, $04
    .byte $00, $09, $09
; Shift 6
    .byte $00, $10, $02
    .byte $00, $22, $11
    .byte $00, $04, $08
    .byte $00, $08, $04
    .byte $00, $03, $30
    .byte $00, $08, $04
    .byte $00, $24, $09
    .byte $00, $12, $12

; Sprite: player (8 lines x 3 bytes x 7 shifts)
spr_player:
; Shift 0
    .byte $00, $02, $00
    .byte $00, $07, $00
    .byte $00, $07, $00
    .byte $78, $7F, $00
    .byte $7C, $7F, $01
    .byte $7C, $7F, $01
    .byte $7C, $7F, $01
    .byte $7C, $7F, $01
; Shift 1
    .byte $00, $04, $00
    .byte $00, $0E, $00
    .byte $00, $0E, $00
    .byte $70, $7F, $01
    .byte $78, $7F, $03
    .byte $78, $7F, $03
    .byte $78, $7F, $03
    .byte $78, $7F, $03
; Shift 2
    .byte $00, $08, $00
    .byte $00, $1C, $00
    .byte $00, $1C, $00
    .byte $60, $7F, $03
    .byte $70, $7F, $07
    .byte $70, $7F, $07
    .byte $70, $7F, $07
    .byte $70, $7F, $07
; Shift 3
    .byte $00, $10, $00
    .byte $00, $38, $00
    .byte $00, $38, $00
    .byte $40, $7F, $07
    .byte $60, $7F, $0F
    .byte $60, $7F, $0F
    .byte $60, $7F, $0F
    .byte $60, $7F, $0F
; Shift 4
    .byte $00, $20, $00
    .byte $00, $70, $00
    .byte $00, $70, $00
    .byte $00, $7F, $0F
    .byte $40, $7F, $1F
    .byte $40, $7F, $1F
    .byte $40, $7F, $1F
    .byte $40, $7F, $1F
; Shift 5
    .byte $00, $40, $00
    .byte $00, $60, $01
    .byte $00, $60, $01
    .byte $00, $7E, $1F
    .byte $00, $7F, $3F
    .byte $00, $7F, $3F
    .byte $00, $7F, $3F
    .byte $00, $7F, $3F
; Shift 6
    .byte $00, $00, $01
    .byte $00, $40, $03
    .byte $00, $40, $03
    .byte $00, $7C, $3F
    .byte $00, $7E, $7F
    .byte $00, $7E, $7F
    .byte $00, $7E, $7F
    .byte $00, $7E, $7F

; Sprite: player_exp0 (8 lines x 3 bytes x 7 shifts)
spr_player_exp0:
; Shift 0
    .byte $40, $00, $00
    .byte $00, $10, $00
    .byte $40, $0A, $00
    .byte $48, $00, $00
    .byte $00, $1B, $00
    .byte $22, $2B, $00
    .byte $78, $4F, $00
    .byte $7C, $5F, $02
; Shift 1
    .byte $00, $01, $00
    .byte $00, $20, $00
    .byte $00, $15, $00
    .byte $10, $01, $00
    .byte $00, $36, $00
    .byte $44, $56, $00
    .byte $70, $1F, $01
    .byte $78, $3F, $05
; Shift 2
    .byte $00, $02, $00
    .byte $00, $40, $00
    .byte $00, $2A, $00
    .byte $20, $02, $00
    .byte $00, $6C, $00
    .byte $08, $2D, $01
    .byte $60, $3F, $02
    .byte $70, $7F, $0A
; Shift 3
    .byte $00, $04, $00
    .byte $00, $00, $01
    .byte $00, $54, $00
    .byte $40, $04, $00
    .byte $00, $58, $01
    .byte $10, $5A, $02
    .byte $40, $7F, $04
    .byte $60, $7F, $15
; Shift 4
    .byte $00, $08, $00
    .byte $00, $00, $02
    .byte $00, $28, $01
    .byte $00, $09, $00
    .byte $00, $30, $03
    .byte $20, $34, $05
    .byte $00, $7F, $09
    .byte $40, $7F, $2B
; Shift 5
    .byte $00, $10, $00
    .byte $00, $00, $04
    .byte $00, $50, $02
    .byte $00, $12, $00
    .byte $00, $60, $06
    .byte $40, $68, $0A
    .byte $00, $7E, $13
    .byte $00, $7F, $57
; Shift 6
    .byte $00, $20, $00
    .byte $00, $00, $08
    .byte $00, $20, $05
    .byte $00, $24, $00
    .byte $00, $40, $0D
    .byte $00, $51, $15
    .byte $00, $7C, $27
    .byte $00, $7E, $2F

; Sprite: player_exp1 (8 lines x 3 bytes x 7 shifts)
spr_player_exp1:
; Shift 0
    .byte $08, $40, $00
    .byte $41, $30, $02
    .byte $08, $06, $00
    .byte $40, $00, $01
    .byte $52, $19, $02
    .byte $04, $47, $00
    .byte $78, $1F, $00
    .byte $6C, $1F, $01
; Shift 1
    .byte $10, $00, $01
    .byte $02, $61, $04
    .byte $10, $0C, $00
    .byte $00, $01, $02
    .byte $24, $33, $04
    .byte $08, $0E, $01
    .byte $70, $3F, $00
    .byte $58, $3F, $02
; Shift 2
    .byte $20, $00, $02
    .byte $04, $42, $09
    .byte $20, $18, $00
    .byte $00, $02, $04
    .byte $48, $66, $08
    .byte $10, $1C, $02
    .byte $60, $7F, $00
    .byte $30, $7F, $04
; Shift 3
    .byte $40, $00, $04
    .byte $08, $04, $13
    .byte $40, $30, $00
    .byte $00, $04, $08
    .byte $10, $4D, $11
    .byte $20, $38, $04
    .byte $40, $7F, $01
    .byte $60, $7E, $09
; Shift 4
    .byte $00, $01, $08
    .byte $10, $08, $26
    .byte $00, $61, $00
    .byte $00, $08, $10
    .byte $20, $1A, $23
    .byte $40, $70, $08
    .byte $00, $7F, $03
    .byte $40, $7D, $13
; Shift 5
    .byte $00, $02, $10
    .byte $20, $10, $4C
    .byte $00, $42, $01
    .byte $00, $10, $20
    .byte $40, $34, $46
    .byte $00, $61, $11
    .byte $00, $7E, $07
    .byte $00, $7B, $27
; Shift 6
    .byte $00, $04, $20
    .byte $40, $20, $18
    .byte $00, $04, $03
    .byte $00, $20, $40
    .byte $00, $69, $0C
    .byte $00, $42, $23
    .byte $00, $7C, $0F
    .byte $00, $76, $4F

; Sprite: saucer (8 lines x 3 bytes x 7 shifts)
spr_saucer:
; Shift 0
    .byte $00, $00, $00
    .byte $60, $0F, $00
    .byte $78, $3F, $00
    .byte $7C, $7F, $00
    .byte $36, $5B, $01
    .byte $7F, $7F, $03
    .byte $1C, $73, $00
    .byte $08, $20, $00
; Shift 1
    .byte $00, $00, $00
    .byte $40, $1F, $00
    .byte $70, $7F, $00
    .byte $78, $7F, $01
    .byte $6C, $36, $03
    .byte $7E, $7F, $07
    .byte $38, $66, $01
    .byte $10, $40, $00
; Shift 2
    .byte $00, $00, $00
    .byte $00, $3F, $00
    .byte $60, $7F, $01
    .byte $70, $7F, $03
    .byte $58, $6D, $06
    .byte $7C, $7F, $0F
    .byte $70, $4C, $03
    .byte $20, $00, $01
; Shift 3
    .byte $00, $00, $00
    .byte $00, $7E, $00
    .byte $40, $7F, $03
    .byte $60, $7F, $07
    .byte $30, $5B, $0D
    .byte $78, $7F, $1F
    .byte $60, $19, $07
    .byte $40, $00, $02
; Shift 4
    .byte $00, $00, $00
    .byte $00, $7C, $01
    .byte $00, $7F, $07
    .byte $40, $7F, $0F
    .byte $60, $36, $1B
    .byte $70, $7F, $3F
    .byte $40, $33, $0E
    .byte $00, $01, $04
; Shift 5
    .byte $00, $00, $00
    .byte $00, $78, $03
    .byte $00, $7E, $0F
    .byte $00, $7F, $1F
    .byte $40, $6D, $36
    .byte $60, $7F, $7F
    .byte $00, $67, $1C
    .byte $00, $02, $08
; Shift 6
    .byte $00, $00, $00
    .byte $00, $70, $07
    .byte $00, $7C, $1F
    .byte $00, $7E, $3F
    .byte $00, $5B, $6D
    .byte $40, $7F, $7F
    .byte $00, $4E, $39
    .byte $00, $04, $10

; Sprite: saucer_exp (8 lines x 3 bytes x 7 shifts)
spr_saucer_exp:
; Shift 0
    .byte $14, $50, $00
    .byte $01, $0C, $02
    .byte $78, $18, $00
    .byte $7C, $73, $00
    .byte $2E, $65, $01
    .byte $78, $31, $00
    .byte $50, $18, $02
    .byte $08, $21, $00
; Shift 1
    .byte $28, $20, $01
    .byte $02, $18, $04
    .byte $70, $31, $00
    .byte $78, $67, $01
    .byte $5C, $4A, $03
    .byte $70, $63, $00
    .byte $20, $31, $04
    .byte $10, $42, $00
; Shift 2
    .byte $50, $40, $02
    .byte $04, $30, $08
    .byte $60, $63, $00
    .byte $70, $4F, $03
    .byte $38, $15, $07
    .byte $60, $47, $01
    .byte $40, $62, $08
    .byte $20, $04, $01
; Shift 3
    .byte $20, $01, $05
    .byte $08, $60, $10
    .byte $40, $47, $01
    .byte $60, $1F, $07
    .byte $70, $2A, $0E
    .byte $40, $0F, $03
    .byte $00, $45, $11
    .byte $40, $08, $02
; Shift 4
    .byte $40, $02, $0A
    .byte $10, $40, $21
    .byte $00, $0F, $03
    .byte $40, $3F, $0E
    .byte $60, $55, $1C
    .byte $00, $1F, $06
    .byte $00, $0A, $23
    .byte $00, $11, $04
; Shift 5
    .byte $00, $05, $14
    .byte $20, $00, $43
    .byte $00, $1E, $06
    .byte $00, $7F, $1C
    .byte $40, $2B, $39
    .byte $00, $3E, $0C
    .byte $00, $14, $46
    .byte $00, $22, $08
; Shift 6
    .byte $00, $0A, $28
    .byte $40, $00, $06
    .byte $00, $3C, $0C
    .byte $00, $7E, $39
    .byte $00, $57, $72
    .byte $00, $7C, $18
    .byte $00, $28, $0C
    .byte $00, $44, $10

bomb_roll_f0:
    .byte $00, $00
    .byte $00, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $38, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $70, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $60, $01
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $40, $03
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $00, $07
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_roll Frame 1 (8 lines x 2 bytes x 7 shifts)
bomb_roll_f1:
    .byte $00, $00
    .byte $08, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $10, $00
    .byte $38, $00
    .byte $10, $00
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $20, $00
    .byte $70, $00
    .byte $20, $00
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $40, $00
    .byte $60, $01
    .byte $40, $00
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $00, $01
    .byte $40, $03
    .byte $00, $01
    .byte $00, $04
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $04
    .byte $00, $02
    .byte $00, $07
    .byte $00, $02
    .byte $00, $08
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_roll Frame 2 (8 lines x 2 bytes x 7 shifts)
bomb_roll_f2:
    .byte $00, $00
    .byte $00, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $38, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $70, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $60, $01
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $40, $03
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $00, $07
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_roll Frame 3 (8 lines x 2 bytes x 7 shifts)
bomb_roll_f3:
    .byte $00, $00
    .byte $10, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $10, $00
    .byte $38, $00
    .byte $10, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $20, $00
    .byte $70, $00
    .byte $20, $00
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $40, $00
    .byte $60, $01
    .byte $40, $00
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $04
    .byte $00, $01
    .byte $40, $03
    .byte $00, $01
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $08
    .byte $00, $02
    .byte $00, $07
    .byte $00, $02
    .byte $00, $04
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_plung Frame 0 (8 lines x 2 bytes x 7 shifts)
bomb_plung_f0:
    .byte $00, $00
    .byte $04, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $04, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $08, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $10, $00
    .byte $38, $00
    .byte $10, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $20, $00
    .byte $70, $00
    .byte $20, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $40, $00
    .byte $60, $01
    .byte $40, $00
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $00, $01
    .byte $40, $03
    .byte $00, $01
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $00, $02
    .byte $00, $07
    .byte $00, $02
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_plung Frame 1 (8 lines x 2 bytes x 7 shifts)
bomb_plung_f1:
    .byte $00, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $38, $00
    .byte $10, $00
    .byte $38, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $70, $00
    .byte $20, $00
    .byte $70, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $60, $01
    .byte $40, $00
    .byte $60, $01
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $40, $03
    .byte $00, $01
    .byte $40, $03
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $00, $07
    .byte $00, $02
    .byte $00, $07
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_plung Frame 2 (8 lines x 2 bytes x 7 shifts)
bomb_plung_f2:
    .byte $00, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $04, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $08, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $38, $00
    .byte $10, $00
    .byte $10, $00
    .byte $10, $00
    .byte $38, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $70, $00
    .byte $20, $00
    .byte $20, $00
    .byte $20, $00
    .byte $70, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $60, $01
    .byte $40, $00
    .byte $40, $00
    .byte $40, $00
    .byte $60, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $03
    .byte $00, $01
    .byte $00, $01
    .byte $00, $01
    .byte $40, $03
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $07
    .byte $00, $02
    .byte $00, $02
    .byte $00, $02
    .byte $00, $07
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_plung Frame 3 (8 lines x 2 bytes x 7 shifts)
bomb_plung_f3:
    .byte $00, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $0E, $00
    .byte $04, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $1C, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $38, $00
    .byte $10, $00
    .byte $38, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $70, $00
    .byte $20, $00
    .byte $70, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $60, $01
    .byte $40, $00
    .byte $60, $01
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $40, $03
    .byte $00, $01
    .byte $40, $03
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $00, $07
    .byte $00, $02
    .byte $00, $07
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_squig Frame 0 (8 lines x 2 bytes x 7 shifts)
bomb_squig_f0:
    .byte $00, $00
    .byte $04, $00
    .byte $02, $00
    .byte $04, $00
    .byte $08, $00
    .byte $04, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $08, $00
    .byte $04, $00
    .byte $08, $00
    .byte $10, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $08, $00
    .byte $10, $00
    .byte $20, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $10, $00
    .byte $20, $00
    .byte $40, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $20, $00
    .byte $40, $00
    .byte $00, $01
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $40, $00
    .byte $00, $01
    .byte $00, $02
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $00, $01
    .byte $00, $02
    .byte $00, $04
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_squig Frame 1 (8 lines x 2 bytes x 7 shifts)
bomb_squig_f1:
    .byte $00, $00
    .byte $08, $00
    .byte $04, $00
    .byte $02, $00
    .byte $04, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $08, $00
    .byte $04, $00
    .byte $08, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $10, $00
    .byte $08, $00
    .byte $10, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $20, $00
    .byte $10, $00
    .byte $20, $00
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $40, $00
    .byte $20, $00
    .byte $40, $00
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $00, $01
    .byte $40, $00
    .byte $00, $01
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $04
    .byte $00, $02
    .byte $00, $01
    .byte $00, $02
    .byte $00, $04
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_squig Frame 2 (8 lines x 2 bytes x 7 shifts)
bomb_squig_f2:
    .byte $00, $00
    .byte $04, $00
    .byte $08, $00
    .byte $04, $00
    .byte $02, $00
    .byte $04, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $08, $00
    .byte $10, $00
    .byte $08, $00
    .byte $04, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $20, $00
    .byte $10, $00
    .byte $08, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $40, $00
    .byte $20, $00
    .byte $10, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $00, $01
    .byte $40, $00
    .byte $20, $00
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $00, $02
    .byte $00, $01
    .byte $40, $00
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $02
    .byte $00, $04
    .byte $00, $02
    .byte $00, $01
    .byte $00, $02
    .byte $00, $00
    .byte $00, $00

; Bomb: bomb_squig Frame 3 (8 lines x 2 bytes x 7 shifts)
bomb_squig_f3:
    .byte $00, $00
    .byte $02, $00
    .byte $04, $00
    .byte $08, $00
    .byte $04, $00
    .byte $02, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $04, $00
    .byte $08, $00
    .byte $10, $00
    .byte $08, $00
    .byte $04, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $08, $00
    .byte $10, $00
    .byte $20, $00
    .byte $10, $00
    .byte $08, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $10, $00
    .byte $20, $00
    .byte $40, $00
    .byte $20, $00
    .byte $10, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $20, $00
    .byte $40, $00
    .byte $00, $01
    .byte $40, $00
    .byte $20, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $40, $00
    .byte $00, $01
    .byte $00, $02
    .byte $00, $01
    .byte $40, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $00
    .byte $00, $01
    .byte $00, $02
    .byte $00, $04
    .byte $00, $02
    .byte $00, $01
    .byte $00, $00
    .byte $00, $00

; ===================================================================
; Authentic 1978 Space Invaders 8x8 Font Glyphs (8 bytes each)
; ===================================================================
font_glyphs:
; Chars mapped in order: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ<>=-:/*? y
font_char_48: ; '0'
    .byte $3C, $66, $76, $7E, $6E, $66, $3C, $00
font_char_49: ; '1'
    .byte $18, $1C, $18, $18, $18, $18, $3C, $00
font_char_50: ; '2'
    .byte $3C, $66, $60, $38, $0C, $06, $7E, $00
font_char_51: ; '3'
    .byte $7E, $60, $30, $38, $60, $66, $3C, $00
font_char_52: ; '4'
    .byte $30, $38, $3C, $36, $7E, $30, $30, $00
font_char_53: ; '5'
    .byte $7E, $06, $3E, $60, $60, $66, $3C, $00
font_char_54: ; '6'
    .byte $78, $0C, $06, $3E, $66, $66, $3C, $00
font_char_55: ; '7'
    .byte $7E, $60, $30, $18, $0C, $0C, $0C, $00
font_char_56: ; '8'
    .byte $3C, $66, $66, $3C, $66, $66, $3C, $00
font_char_57: ; '9'
    .byte $3C, $66, $66, $7C, $60, $30, $1E, $00
font_char_65: ; 'A'
    .byte $18, $3C, $66, $66, $7E, $66, $66, $00
font_char_66: ; 'B'
    .byte $3E, $66, $66, $3E, $66, $66, $3E, $00
font_char_67: ; 'C'
    .byte $3C, $66, $06, $06, $06, $66, $3C, $00
font_char_68: ; 'D'
    .byte $3E, $66, $66, $66, $66, $66, $3E, $00
font_char_69: ; 'E'
    .byte $7E, $06, $06, $3E, $06, $06, $7E, $00
font_char_70: ; 'F'
    .byte $7E, $06, $06, $3E, $06, $06, $06, $00
font_char_71: ; 'G'
    .byte $7C, $06, $06, $06, $76, $66, $7C, $00
font_char_72: ; 'H'
    .byte $66, $66, $66, $7E, $66, $66, $66, $00
font_char_73: ; 'I'
    .byte $3C, $18, $18, $18, $18, $18, $3C, $00
font_char_74: ; 'J'
    .byte $60, $60, $60, $60, $60, $66, $3C, $00
font_char_75: ; 'K'
    .byte $66, $36, $1E, $0E, $1E, $36, $66, $00
font_char_76: ; 'L'
    .byte $06, $06, $06, $06, $06, $06, $7E, $00
font_char_77: ; 'M'
    .byte $66, $7E, $7E, $7E, $66, $66, $66, $00
font_char_78: ; 'N'
    .byte $66, $66, $6E, $7E, $76, $66, $66, $00
font_char_79: ; 'O'
    .byte $3C, $66, $66, $66, $66, $66, $3C, $00
font_char_80: ; 'P'
    .byte $3E, $66, $66, $3E, $06, $06, $06, $00
font_char_81: ; 'Q'
    .byte $3C, $66, $66, $66, $7E, $36, $7C, $00
font_char_82: ; 'R'
    .byte $3E, $66, $66, $3E, $1E, $36, $66, $00
font_char_83: ; 'S'
    .byte $3C, $66, $06, $3C, $60, $66, $3C, $00
font_char_84: ; 'T'
    .byte $7E, $18, $18, $18, $18, $18, $18, $00
font_char_85: ; 'U'
    .byte $66, $66, $66, $66, $66, $66, $3C, $00
font_char_86: ; 'V'
    .byte $66, $66, $66, $66, $66, $3C, $18, $00
font_char_87: ; 'W'
    .byte $66, $66, $66, $7E, $7E, $7E, $66, $00
font_char_88: ; 'X'
    .byte $66, $66, $3C, $18, $3C, $66, $66, $00
font_char_89: ; 'Y'
    .byte $66, $66, $3C, $18, $18, $18, $18, $00
font_char_90: ; 'Z'
    .byte $7E, $60, $30, $18, $0C, $06, $7E, $00
font_char_60: ; '<'
    .byte $30, $18, $0C, $06, $0C, $18, $30, $00
font_char_62: ; '>'
    .byte $0C, $18, $30, $60, $30, $18, $0C, $00
font_char_61: ; '='
    .byte $00, $00, $7E, $00, $7E, $00, $00, $00
font_char_45: ; '-'
    .byte $00, $00, $00, $7E, $00, $00, $00, $00
font_char_58: ; ':'
    .byte $00, $38, $38, $00, $38, $38, $00, $00
font_char_47: ; '/'
    .byte $60, $30, $18, $0C, $06, $00, $00, $00
font_char_42: ; '*'
    .byte $18, $7E, $3C, $18, $3C, $7E, $18, $00
font_char_63: ; '?'
    .byte $3C, $66, $30, $18, $18, $00, $18, $00
font_char_space: ; ' '
    .byte $00, $00, $00, $00, $00, $00, $00, $00
font_char_121: ; 'y' (upside-down)
    .byte $18, $18, $18, $18, $3C, $66, $66, $00
font_char_39: ; ''' (apostrophe, index 46)
    .byte $18, $18, $08, $00, $00, $00, $00, $00

; ===================================================================
; Authentic Bunker Template (16 scanlines x 4 bytes each = 64 bytes)
; ===================================================================
bunker_template:
    .byte $70, $7F, $0F, $00 ; Line 0
    .byte $78, $7F, $1F, $00 ; Line 1
    .byte $7C, $7F, $3F, $00 ; Line 2
    .byte $7E, $7F, $7F, $00 ; Line 3
    .byte $7F, $7F, $7F, $01 ; Line 4
    .byte $7F, $7F, $7F, $01 ; Line 5
    .byte $7F, $7F, $7F, $01 ; Line 6
    .byte $7F, $7F, $7F, $01 ; Line 7
    .byte $7F, $7F, $7F, $01 ; Line 8
    .byte $7F, $7F, $7F, $01 ; Line 9
    .byte $7F, $00, $7E, $01 ; Line 10
    .byte $7F, $00, $7E, $01 ; Line 11
    .byte $7F, $00, $7E, $01 ; Line 12
    .byte $7F, $00, $7E, $01 ; Line 13
    .byte $7F, $00, $7E, $01 ; Line 14
    .byte $7F, $00, $7E, $01 ; Line 15

; ===================================================================
; Authentic 1978 ROM Firing Tables & Saucer Score Table
; ===================================================================
col_fire_table:
    .byte $01, $07, $01, $01, $01, $04, $0B, $01, $06, $03, $01, $01, $0B, $09, $02, $08, $02, $0B, $04, $07, $0A, $05, $02, $05, $04, $06, $07, $08, $0A, $06, $0A, $03

saucer_score_table:
saucer_score_lo: ; BCD low (e.g. $50, $00)
    .byte $00, $50, $50, $00, $50, $00, $00, $50, $00, $00, $00, $00, $50, $50, $00
saucer_score_hi: ; BCD high (e.g. $00, $01, $03)
    .byte $01, $00, $00, $01, $01, $01, $01, $00, $03, $01, $01, $01, $00, $01, $01

; ===================================================================
; AUTHENTIC 1978 ATTRACT ANIMATION SPRITES (PULL / PUSH 'Y')
; ===================================================================

; Sprite: spr_squid_pull_y_f0 (8 lines x 3 bytes x 7 shifts)
spr_squid_pull_y_f0:
; Shift 0
    .byte $18, $18, $00
    .byte $18, $3C, $00
    .byte $18, $7E, $00
    .byte $18, $5B, $01
    .byte $3C, $7F, $01
    .byte $66, $5A, $00
    .byte $66, $01, $01
    .byte $00, $42, $00
; Shift 1
    .byte $30, $30, $00
    .byte $30, $78, $00
    .byte $30, $7C, $01
    .byte $30, $36, $03
    .byte $78, $7E, $03
    .byte $4C, $35, $01
    .byte $4C, $03, $02
    .byte $00, $04, $01
; Shift 2
    .byte $60, $60, $00
    .byte $60, $70, $01
    .byte $60, $78, $03
    .byte $60, $6C, $06
    .byte $70, $7D, $07
    .byte $18, $6B, $02
    .byte $18, $07, $04
    .byte $00, $08, $02
; Shift 3
    .byte $40, $41, $01
    .byte $40, $61, $03
    .byte $40, $71, $07
    .byte $40, $59, $0D
    .byte $60, $7B, $0F
    .byte $30, $56, $05
    .byte $30, $0E, $08
    .byte $00, $10, $04
; Shift 4
    .byte $00, $03, $03
    .byte $00, $43, $07
    .byte $00, $63, $0F
    .byte $00, $33, $1B
    .byte $40, $77, $1F
    .byte $60, $2C, $0B
    .byte $60, $1C, $10
    .byte $00, $20, $08
; Shift 5
    .byte $00, $06, $06
    .byte $00, $06, $0F
    .byte $00, $46, $1F
    .byte $00, $66, $36
    .byte $00, $6F, $3F
    .byte $40, $59, $16
    .byte $40, $39, $20
    .byte $00, $40, $10
; Shift 6
    .byte $00, $0C, $0C
    .byte $00, $0C, $1E
    .byte $00, $0C, $3F
    .byte $00, $4C, $6D
    .byte $00, $5E, $7F
    .byte $00, $33, $2D
    .byte $00, $73, $40
    .byte $00, $00, $21

; Sprite: spr_squid_pull_y_f1 (8 lines x 3 bytes x 7 shifts)
spr_squid_pull_y_f1:
; Shift 0
    .byte $18, $18, $00
    .byte $18, $3C, $00
    .byte $18, $7E, $00
    .byte $18, $5B, $01
    .byte $3C, $7F, $01
    .byte $66, $24, $00
    .byte $66, $5A, $00
    .byte $00, $25, $01
; Shift 1
    .byte $30, $30, $00
    .byte $30, $78, $00
    .byte $30, $7C, $01
    .byte $30, $36, $03
    .byte $78, $7E, $03
    .byte $4C, $49, $00
    .byte $4C, $35, $01
    .byte $00, $4A, $02
; Shift 2
    .byte $60, $60, $00
    .byte $60, $70, $01
    .byte $60, $78, $03
    .byte $60, $6C, $06
    .byte $70, $7D, $07
    .byte $18, $13, $01
    .byte $18, $6B, $02
    .byte $00, $14, $05
; Shift 3
    .byte $40, $41, $01
    .byte $40, $61, $03
    .byte $40, $71, $07
    .byte $40, $59, $0D
    .byte $60, $7B, $0F
    .byte $30, $26, $02
    .byte $30, $56, $05
    .byte $00, $28, $0A
; Shift 4
    .byte $00, $03, $03
    .byte $00, $43, $07
    .byte $00, $63, $0F
    .byte $00, $33, $1B
    .byte $40, $77, $1F
    .byte $60, $4C, $04
    .byte $60, $2C, $0B
    .byte $00, $50, $14
; Shift 5
    .byte $00, $06, $06
    .byte $00, $06, $0F
    .byte $00, $46, $1F
    .byte $00, $66, $36
    .byte $00, $6F, $3F
    .byte $40, $19, $09
    .byte $40, $59, $16
    .byte $00, $20, $29
; Shift 6
    .byte $00, $0C, $0C
    .byte $00, $0C, $1E
    .byte $00, $0C, $3F
    .byte $00, $4C, $6D
    .byte $00, $5E, $7F
    .byte $00, $33, $12
    .byte $00, $33, $2D
    .byte $00, $40, $52

; Sprite: spr_squid_push_y_f0 (8 lines x 3 bytes x 7 shifts)
spr_squid_push_y_f0:
; Shift 0
    .byte $66, $18, $00
    .byte $66, $3C, $00
    .byte $3C, $7E, $00
    .byte $18, $5B, $01
    .byte $18, $7F, $01
    .byte $18, $5A, $00
    .byte $18, $01, $01
    .byte $00, $42, $00
; Shift 1
    .byte $4C, $31, $00
    .byte $4C, $79, $00
    .byte $78, $7C, $01
    .byte $30, $36, $03
    .byte $30, $7E, $03
    .byte $30, $34, $01
    .byte $30, $02, $02
    .byte $00, $04, $01
; Shift 2
    .byte $18, $63, $00
    .byte $18, $73, $01
    .byte $70, $79, $03
    .byte $60, $6C, $06
    .byte $60, $7C, $07
    .byte $60, $68, $02
    .byte $60, $04, $04
    .byte $00, $08, $02
; Shift 3
    .byte $30, $46, $01
    .byte $30, $66, $03
    .byte $60, $73, $07
    .byte $40, $59, $0D
    .byte $40, $79, $0F
    .byte $40, $51, $05
    .byte $40, $09, $08
    .byte $00, $10, $04
; Shift 4
    .byte $60, $0C, $03
    .byte $60, $4C, $07
    .byte $40, $67, $0F
    .byte $00, $33, $1B
    .byte $00, $73, $1F
    .byte $00, $23, $0B
    .byte $00, $13, $10
    .byte $00, $20, $08
; Shift 5
    .byte $40, $19, $06
    .byte $40, $19, $0F
    .byte $00, $4F, $1F
    .byte $00, $66, $36
    .byte $00, $66, $3F
    .byte $00, $46, $16
    .byte $00, $26, $20
    .byte $00, $40, $10
; Shift 6
    .byte $00, $33, $0C
    .byte $00, $33, $1E
    .byte $00, $1E, $3F
    .byte $00, $4C, $6D
    .byte $00, $4C, $7F
    .byte $00, $0C, $2D
    .byte $00, $4C, $40
    .byte $00, $00, $21

; Sprite: spr_squid_push_y_f1 (8 lines x 3 bytes x 7 shifts)
spr_squid_push_y_f1:
; Shift 0
    .byte $66, $18, $00
    .byte $66, $3C, $00
    .byte $3C, $7E, $00
    .byte $18, $5B, $01
    .byte $18, $7F, $01
    .byte $18, $24, $00
    .byte $18, $5A, $00
    .byte $00, $25, $01
; Shift 1
    .byte $4C, $31, $00
    .byte $4C, $79, $00
    .byte $78, $7C, $01
    .byte $30, $36, $03
    .byte $30, $7E, $03
    .byte $30, $48, $00
    .byte $30, $34, $01
    .byte $00, $4A, $02
; Shift 2
    .byte $18, $63, $00
    .byte $18, $73, $01
    .byte $70, $79, $03
    .byte $60, $6C, $06
    .byte $60, $7C, $07
    .byte $60, $10, $01
    .byte $60, $68, $02
    .byte $00, $14, $05
; Shift 3
    .byte $30, $46, $01
    .byte $30, $66, $03
    .byte $60, $73, $07
    .byte $40, $59, $0D
    .byte $40, $79, $0F
    .byte $40, $21, $02
    .byte $40, $51, $05
    .byte $00, $28, $0A
; Shift 4
    .byte $60, $0C, $03
    .byte $60, $4C, $07
    .byte $40, $67, $0F
    .byte $00, $33, $1B
    .byte $00, $73, $1F
    .byte $00, $43, $04
    .byte $00, $23, $0B
    .byte $00, $50, $14
; Shift 5
    .byte $40, $19, $06
    .byte $40, $19, $0F
    .byte $00, $4F, $1F
    .byte $00, $66, $36
    .byte $00, $66, $3F
    .byte $00, $06, $09
    .byte $00, $46, $16
    .byte $00, $20, $29
; Shift 6
    .byte $00, $33, $0C
    .byte $00, $33, $1E
    .byte $00, $1E, $3F
    .byte $00, $4C, $6D
    .byte $00, $4C, $7F
    .byte $00, $0C, $12
    .byte $00, $0C, $2D
    .byte $00, $40, $52


; Bunker collision hit test mask (3 pixels centered at local_x 0..27)
bunker_hit_mask_table:
    .byte $03, $00, $00, $00 ; X=0
    .byte $07, $00, $00, $00 ; X=1
    .byte $0E, $00, $00, $00 ; X=2
    .byte $1C, $00, $00, $00 ; X=3
    .byte $38, $00, $00, $00 ; X=4
    .byte $70, $00, $00, $00 ; X=5
    .byte $60, $01, $00, $00 ; X=6
    .byte $40, $03, $00, $00 ; X=7
    .byte $00, $07, $00, $00 ; X=8
    .byte $00, $0E, $00, $00 ; X=9
    .byte $00, $1C, $00, $00 ; X=10
    .byte $00, $38, $00, $00 ; X=11
    .byte $00, $70, $00, $00 ; X=12
    .byte $00, $60, $01, $00 ; X=13
    .byte $00, $40, $03, $00 ; X=14
    .byte $00, $00, $07, $00 ; X=15
    .byte $00, $00, $0E, $00 ; X=16
    .byte $00, $00, $1C, $00 ; X=17
    .byte $00, $00, $38, $00 ; X=18
    .byte $00, $00, $70, $00 ; X=19
    .byte $00, $00, $60, $01 ; X=20
    .byte $00, $00, $40, $03 ; X=21
    .byte $00, $00, $00, $07 ; X=22
    .byte $00, $00, $00, $0E ; X=23
    .byte $00, $00, $00, $1C ; X=24
    .byte $00, $00, $00, $38 ; X=25
    .byte $00, $00, $00, $70 ; X=26
    .byte $00, $00, $00, $60 ; X=27

; Bunker crater width 5 mask (5 pixels centered at local_x 0..27)
bunker_crater_w5_table:
    .byte $78, $7F, $7F, $7F ; X=0
    .byte $70, $7F, $7F, $7F ; X=1
    .byte $60, $7F, $7F, $7F ; X=2
    .byte $41, $7F, $7F, $7F ; X=3
    .byte $03, $7F, $7F, $7F ; X=4
    .byte $07, $7E, $7F, $7F ; X=5
    .byte $0F, $7C, $7F, $7F ; X=6
    .byte $1F, $78, $7F, $7F ; X=7
    .byte $3F, $70, $7F, $7F ; X=8
    .byte $7F, $60, $7F, $7F ; X=9
    .byte $7F, $41, $7F, $7F ; X=10
    .byte $7F, $03, $7F, $7F ; X=11
    .byte $7F, $07, $7E, $7F ; X=12
    .byte $7F, $0F, $7C, $7F ; X=13
    .byte $7F, $1F, $78, $7F ; X=14
    .byte $7F, $3F, $70, $7F ; X=15
    .byte $7F, $7F, $60, $7F ; X=16
    .byte $7F, $7F, $41, $7F ; X=17
    .byte $7F, $7F, $03, $7F ; X=18
    .byte $7F, $7F, $07, $7E ; X=19
    .byte $7F, $7F, $0F, $7C ; X=20
    .byte $7F, $7F, $1F, $78 ; X=21
    .byte $7F, $7F, $3F, $70 ; X=22
    .byte $7F, $7F, $7F, $60 ; X=23
    .byte $7F, $7F, $7F, $41 ; X=24
    .byte $7F, $7F, $7F, $03 ; X=25
    .byte $7F, $7F, $7F, $07 ; X=26
    .byte $7F, $7F, $7F, $0F ; X=27

; Bunker crater width 3 mask (3 pixels centered at local_x 0..27)
bunker_crater_w3_table:
    .byte $7C, $7F, $7F, $7F ; X=0
    .byte $78, $7F, $7F, $7F ; X=1
    .byte $71, $7F, $7F, $7F ; X=2
    .byte $63, $7F, $7F, $7F ; X=3
    .byte $47, $7F, $7F, $7F ; X=4
    .byte $0F, $7F, $7F, $7F ; X=5
    .byte $1F, $7E, $7F, $7F ; X=6
    .byte $3F, $7C, $7F, $7F ; X=7
    .byte $7F, $78, $7F, $7F ; X=8
    .byte $7F, $71, $7F, $7F ; X=9
    .byte $7F, $63, $7F, $7F ; X=10
    .byte $7F, $47, $7F, $7F ; X=11
    .byte $7F, $0F, $7F, $7F ; X=12
    .byte $7F, $1F, $7E, $7F ; X=13
    .byte $7F, $3F, $7C, $7F ; X=14
    .byte $7F, $7F, $78, $7F ; X=15
    .byte $7F, $7F, $71, $7F ; X=16
    .byte $7F, $7F, $63, $7F ; X=17
    .byte $7F, $7F, $47, $7F ; X=18
    .byte $7F, $7F, $0F, $7F ; X=19
    .byte $7F, $7F, $1F, $7E ; X=20
    .byte $7F, $7F, $3F, $7C ; X=21
    .byte $7F, $7F, $7F, $78 ; X=22
    .byte $7F, $7F, $7F, $71 ; X=23
    .byte $7F, $7F, $7F, $63 ; X=24
    .byte $7F, $7F, $7F, $47 ; X=25
    .byte $7F, $7F, $7F, $0F ; X=26
    .byte $7F, $7F, $7F, $1F ; X=27

; Bunker crater width 1 mask (1 pixel at local_x 0..27)
bunker_crater_w1_table:
    .byte $7E, $7F, $7F, $7F ; X=0
    .byte $7D, $7F, $7F, $7F ; X=1
    .byte $7B, $7F, $7F, $7F ; X=2
    .byte $77, $7F, $7F, $7F ; X=3
    .byte $6F, $7F, $7F, $7F ; X=4
    .byte $5F, $7F, $7F, $7F ; X=5
    .byte $3F, $7F, $7F, $7F ; X=6
    .byte $7F, $7E, $7F, $7F ; X=7
    .byte $7F, $7D, $7F, $7F ; X=8
    .byte $7F, $7B, $7F, $7F ; X=9
    .byte $7F, $77, $7F, $7F ; X=10
    .byte $7F, $6F, $7F, $7F ; X=11
    .byte $7F, $5F, $7F, $7F ; X=12
    .byte $7F, $3F, $7F, $7F ; X=13
    .byte $7F, $7F, $7E, $7F ; X=14
    .byte $7F, $7F, $7D, $7F ; X=15
    .byte $7F, $7F, $7B, $7F ; X=16
    .byte $7F, $7F, $77, $7F ; X=17
    .byte $7F, $7F, $6F, $7F ; X=18
    .byte $7F, $7F, $5F, $7F ; X=19
    .byte $7F, $7F, $3F, $7F ; X=20
    .byte $7F, $7F, $7F, $7E ; X=21
    .byte $7F, $7F, $7F, $7D ; X=22
    .byte $7F, $7F, $7F, $7B ; X=23
    .byte $7F, $7F, $7F, $77 ; X=24
    .byte $7F, $7F, $7F, $6F ; X=25
    .byte $7F, $7F, $7F, $5F ; X=26
    .byte $7F, $7F, $7F, $3F ; X=27
