; ===================================================================
; PANG_DATA.ASM - Full color sprites, HGR tables & ASCII font for Pang!
; Generated by build_pang_assets.py
; ===================================================================

; HGR Scanline Base Addresses (0..191) for Page 1 ($2000)
hgr_lo:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $80, $80, $80, $80, $80, $80, $80, $80
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $80, $80, $80, $80, $80, $80, $80, $80
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $80, $80, $80, $80, $80, $80, $80, $80
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $80, $80, $80, $80, $80, $80, $80, $80
    .byte $28, $28, $28, $28, $28, $28, $28, $28, $A8, $A8, $A8, $A8, $A8, $A8, $A8, $A8
    .byte $28, $28, $28, $28, $28, $28, $28, $28, $A8, $A8, $A8, $A8, $A8, $A8, $A8, $A8
    .byte $28, $28, $28, $28, $28, $28, $28, $28, $A8, $A8, $A8, $A8, $A8, $A8, $A8, $A8
    .byte $28, $28, $28, $28, $28, $28, $28, $28, $A8, $A8, $A8, $A8, $A8, $A8, $A8, $A8
    .byte $50, $50, $50, $50, $50, $50, $50, $50, $D0, $D0, $D0, $D0, $D0, $D0, $D0, $D0
    .byte $50, $50, $50, $50, $50, $50, $50, $50, $D0, $D0, $D0, $D0, $D0, $D0, $D0, $D0
    .byte $50, $50, $50, $50, $50, $50, $50, $50, $D0, $D0, $D0, $D0, $D0, $D0, $D0, $D0
    .byte $50, $50, $50, $50, $50, $50, $50, $50, $D0, $D0, $D0, $D0, $D0, $D0, $D0, $D0

hgr_hi:
    .byte $20, $24, $28, $2C, $30, $34, $38, $3C, $20, $24, $28, $2C, $30, $34, $38, $3C
    .byte $21, $25, $29, $2D, $31, $35, $39, $3D, $21, $25, $29, $2D, $31, $35, $39, $3D
    .byte $22, $26, $2A, $2E, $32, $36, $3A, $3E, $22, $26, $2A, $2E, $32, $36, $3A, $3E
    .byte $23, $27, $2B, $2F, $33, $37, $3B, $3F, $23, $27, $2B, $2F, $33, $37, $3B, $3F
    .byte $20, $24, $28, $2C, $30, $34, $38, $3C, $20, $24, $28, $2C, $30, $34, $38, $3C
    .byte $21, $25, $29, $2D, $31, $35, $39, $3D, $21, $25, $29, $2D, $31, $35, $39, $3D
    .byte $22, $26, $2A, $2E, $32, $36, $3A, $3E, $22, $26, $2A, $2E, $32, $36, $3A, $3E
    .byte $23, $27, $2B, $2F, $33, $37, $3B, $3F, $23, $27, $2B, $2F, $33, $37, $3B, $3F
    .byte $20, $24, $28, $2C, $30, $34, $38, $3C, $20, $24, $28, $2C, $30, $34, $38, $3C
    .byte $21, $25, $29, $2D, $31, $35, $39, $3D, $21, $25, $29, $2D, $31, $35, $39, $3D
    .byte $22, $26, $2A, $2E, $32, $36, $3A, $3E, $22, $26, $2A, $2E, $32, $36, $3A, $3E
    .byte $23, $27, $2B, $2F, $33, $37, $3B, $3F, $23, $27, $2B, $2F, $33, $37, $3B, $3F

; Precalculated scanline multiplication tables
mult2_table:
    .byte 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62
mult3_table:
    .byte 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93
mult4_table:
    .byte 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 112, 116, 120, 124
mult5_table:
    .byte 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155

shift_player_offset_lo:
    .byte $00, $3C, $78, $B4, $F0, $2C, $68
shift_player_offset_hi:
    .byte $00, $00, $00, $00, $00, $01, $01

shift_harpoon_offset_lo:
    .byte $00, $10, $20, $30, $40, $50, $60
shift_harpoon_offset_hi:
    .byte $00, $00, $00, $00, $00, $00, $00

shift_pop_offset_lo:
    .byte $00, $10, $20, $30, $40, $50, $60
shift_pop_offset_hi:
    .byte $00, $00, $00, $00, $00, $00, $00

shift_ball0_offset_lo:
    .byte $00, $10, $20, $30, $40, $50, $60
shift_ball0_offset_hi:
    .byte $00, $00, $00, $00, $00, $00, $00

shift_ball1_offset_lo:
    .byte $00, $2A, $54, $7E, $A8, $D2, $FC
shift_ball1_offset_hi:
    .byte $00, $00, $00, $00, $00, $00, $00

shift_ball2_offset_lo:
    .byte $00, $50, $A0, $F0, $40, $90, $E0
shift_ball2_offset_hi:
    .byte $00, $00, $00, $00, $01, $01, $01

shift_ball3_offset_lo:
    .byte $00, $82, $04, $86, $08, $8A, $0C
shift_ball3_offset_hi:
    .byte $00, $00, $01, $01, $02, $02, $03

; Sprite: spr_player_stand (20 lines x 3 bytes x 7 shifts)
spr_player_stand:
; Shift 0
    .byte $A8, $85, $00
    .byte $AC, $8D, $00
    .byte $A8, $9D, $00
    .byte $E4, $93, $00
    .byte $AC, $9A, $00
    .byte $B8, $8E, $00
    .byte $F0, $83, $00
    .byte $A4, $89, $00
    .byte $A6, $99, $00
    .byte $A5, $A9, $00
    .byte $F5, $95, $00
    .byte $94, $85, $00
    .byte $B4, $8B, $00
    .byte $94, $8A, $00
    .byte $94, $8A, $00
    .byte $88, $84, $00
    .byte $98, $86, $00
    .byte $8C, $8C, $00
    .byte $8E, $9C, $00
    .byte $8A, $94, $00
; Shift 1
    .byte $D0, $8A, $00
    .byte $D8, $9A, $00
    .byte $D0, $BA, $00
    .byte $C8, $A7, $00
    .byte $D8, $B4, $00
    .byte $F0, $9C, $00
    .byte $E0, $87, $00
    .byte $C8, $92, $00
    .byte $CC, $B2, $00
    .byte $CA, $D2, $00
    .byte $EA, $AB, $00
    .byte $A8, $8A, $00
    .byte $E8, $96, $00
    .byte $A8, $94, $00
    .byte $A8, $94, $00
    .byte $90, $88, $00
    .byte $B0, $8C, $00
    .byte $98, $98, $00
    .byte $9C, $B8, $00
    .byte $94, $A8, $00
; Shift 2
    .byte $A0, $95, $00
    .byte $B0, $B5, $00
    .byte $A0, $F5, $00
    .byte $90, $CF, $00
    .byte $B0, $E9, $00
    .byte $E0, $B9, $00
    .byte $C0, $8F, $00
    .byte $90, $A5, $00
    .byte $98, $E5, $00
    .byte $94, $A5, $81
    .byte $D4, $D7, $00
    .byte $D0, $94, $00
    .byte $D0, $AD, $00
    .byte $D0, $A8, $00
    .byte $D0, $A8, $00
    .byte $A0, $90, $00
    .byte $E0, $98, $00
    .byte $B0, $B0, $00
    .byte $B8, $F0, $00
    .byte $A8, $D0, $00
; Shift 3
    .byte $C0, $AA, $00
    .byte $E0, $EA, $00
    .byte $C0, $EA, $81
    .byte $A0, $9E, $81
    .byte $E0, $D2, $81
    .byte $C0, $F3, $00
    .byte $00, $9F, $00
    .byte $A0, $CA, $00
    .byte $B0, $CA, $81
    .byte $A8, $CA, $82
    .byte $A8, $AF, $81
    .byte $A0, $A9, $00
    .byte $A0, $DB, $00
    .byte $A0, $D1, $00
    .byte $A0, $D1, $00
    .byte $C0, $A0, $00
    .byte $C0, $B1, $00
    .byte $E0, $E0, $00
    .byte $F0, $E0, $81
    .byte $D0, $A0, $81
; Shift 4
    .byte $00, $D5, $00
    .byte $C0, $D5, $81
    .byte $00, $D5, $83
    .byte $C0, $BC, $82
    .byte $C0, $A5, $83
    .byte $00, $E7, $81
    .byte $00, $BE, $00
    .byte $C0, $94, $81
    .byte $E0, $94, $83
    .byte $D0, $94, $85
    .byte $D0, $DE, $82
    .byte $C0, $D2, $00
    .byte $C0, $B6, $81
    .byte $C0, $A2, $81
    .byte $C0, $A2, $81
    .byte $00, $C1, $00
    .byte $00, $E3, $00
    .byte $C0, $C1, $81
    .byte $E0, $C1, $83
    .byte $A0, $C1, $82
; Shift 5
    .byte $00, $AA, $81
    .byte $00, $AB, $83
    .byte $00, $AA, $87
    .byte $00, $F9, $84
    .byte $00, $CB, $86
    .byte $00, $CE, $83
    .byte $00, $FC, $00
    .byte $00, $A9, $82
    .byte $C0, $A9, $86
    .byte $A0, $A9, $8A
    .byte $A0, $BD, $85
    .byte $00, $A5, $81
    .byte $00, $ED, $82
    .byte $00, $C5, $82
    .byte $00, $C5, $82
    .byte $00, $82, $81
    .byte $00, $C6, $81
    .byte $00, $83, $83
    .byte $C0, $83, $87
    .byte $C0, $82, $85
; Shift 6
    .byte $00, $D4, $82
    .byte $00, $D6, $86
    .byte $00, $D4, $8E
    .byte $00, $F2, $89
    .byte $00, $96, $8D
    .byte $00, $9C, $87
    .byte $00, $F8, $81
    .byte $00, $D2, $84
    .byte $00, $D3, $8C
    .byte $C0, $D2, $94
    .byte $C0, $FA, $8A
    .byte $00, $CA, $82
    .byte $00, $DA, $85
    .byte $00, $8A, $85
    .byte $00, $8A, $85
    .byte $00, $84, $82
    .byte $00, $8C, $83
    .byte $00, $86, $86
    .byte $00, $87, $8E
    .byte $00, $85, $8A

; Sprite: spr_player_walk1 (20 lines x 3 bytes x 7 shifts)
spr_player_walk1:
; Shift 0
    .byte $A8, $85, $00
    .byte $AC, $8D, $00
    .byte $A8, $9D, $00
    .byte $E4, $93, $00
    .byte $D8, $86, $00
    .byte $F0, $83, $00
    .byte $F0, $81, $00
    .byte $A4, $89, $00
    .byte $A6, $B1, $00
    .byte $A5, $A9, $00
    .byte $F4, $85, $00
    .byte $B4, $83, $00
    .byte $8A, $8A, $00
    .byte $8A, $94, $00
    .byte $84, $88, $00
    .byte $86, $8C, $00
    .byte $87, $8C, $00
    .byte $85, $B8, $00
    .byte $00, $B8, $00
    .byte $85, $A8, $00
; Shift 1
    .byte $D0, $8A, $00
    .byte $D8, $9A, $00
    .byte $D0, $BA, $00
    .byte $C8, $A7, $00
    .byte $B0, $8D, $00
    .byte $E0, $87, $00
    .byte $E0, $83, $00
    .byte $C8, $92, $00
    .byte $CC, $E2, $00
    .byte $CA, $D2, $00
    .byte $E8, $8B, $00
    .byte $E8, $86, $00
    .byte $94, $94, $00
    .byte $94, $A8, $00
    .byte $88, $90, $00
    .byte $8C, $98, $00
    .byte $8E, $98, $00
    .byte $8A, $F0, $00
    .byte $00, $F0, $00
    .byte $8A, $D0, $00
; Shift 2
    .byte $A0, $95, $00
    .byte $B0, $B5, $00
    .byte $A0, $F5, $00
    .byte $90, $CF, $00
    .byte $E0, $9A, $00
    .byte $C0, $8F, $00
    .byte $C0, $87, $00
    .byte $90, $A5, $00
    .byte $98, $C5, $81
    .byte $94, $A5, $81
    .byte $D0, $97, $00
    .byte $D0, $8D, $00
    .byte $A8, $A8, $00
    .byte $A8, $D0, $00
    .byte $90, $A0, $00
    .byte $98, $B0, $00
    .byte $9C, $B0, $00
    .byte $94, $E0, $81
    .byte $00, $E0, $81
    .byte $94, $A0, $81
; Shift 3
    .byte $C0, $AA, $00
    .byte $E0, $EA, $00
    .byte $C0, $EA, $81
    .byte $A0, $9E, $81
    .byte $C0, $B5, $00
    .byte $00, $9F, $00
    .byte $00, $8F, $00
    .byte $A0, $CA, $00
    .byte $B0, $8A, $83
    .byte $A8, $CA, $82
    .byte $A0, $AF, $00
    .byte $A0, $9B, $00
    .byte $D0, $D0, $00
    .byte $D0, $A0, $81
    .byte $A0, $C0, $00
    .byte $B0, $E0, $00
    .byte $B8, $E0, $00
    .byte $A8, $C0, $83
    .byte $00, $C0, $83
    .byte $A8, $C0, $82
; Shift 4
    .byte $00, $D5, $00
    .byte $C0, $D5, $81
    .byte $00, $D5, $83
    .byte $C0, $BC, $82
    .byte $00, $EB, $00
    .byte $00, $BE, $00
    .byte $00, $9E, $00
    .byte $C0, $94, $81
    .byte $E0, $94, $86
    .byte $D0, $94, $85
    .byte $C0, $DE, $00
    .byte $C0, $B6, $00
    .byte $A0, $A1, $81
    .byte $A0, $C1, $82
    .byte $C0, $00, $81
    .byte $E0, $C0, $81
    .byte $F0, $C0, $81
    .byte $D0, $00, $87
    .byte $00, $00, $87
    .byte $D0, $00, $85
; Shift 5
    .byte $00, $AA, $81
    .byte $00, $AB, $83
    .byte $00, $AA, $87
    .byte $00, $F9, $84
    .byte $00, $D6, $81
    .byte $00, $FC, $00
    .byte $00, $BC, $00
    .byte $00, $A9, $82
    .byte $C0, $A9, $8C
    .byte $A0, $A9, $8A
    .byte $00, $BD, $81
    .byte $00, $ED, $00
    .byte $C0, $C2, $82
    .byte $C0, $82, $85
    .byte $00, $81, $82
    .byte $C0, $81, $83
    .byte $E0, $81, $83
    .byte $A0, $81, $8E
    .byte $00, $00, $8E
    .byte $A0, $81, $8A
; Shift 6
    .byte $00, $D4, $82
    .byte $00, $D6, $86
    .byte $00, $D4, $8E
    .byte $00, $F2, $89
    .byte $00, $AC, $83
    .byte $00, $F8, $81
    .byte $00, $F8, $00
    .byte $00, $D2, $84
    .byte $00, $D3, $98
    .byte $C0, $D2, $94
    .byte $00, $FA, $82
    .byte $00, $DA, $81
    .byte $00, $85, $85
    .byte $00, $85, $8A
    .byte $00, $82, $84
    .byte $00, $83, $86
    .byte $C0, $83, $86
    .byte $C0, $82, $9C
    .byte $00, $00, $9C
    .byte $C0, $82, $94

; Sprite: spr_player_walk2 (20 lines x 3 bytes x 7 shifts)
spr_player_walk2:
; Shift 0
    .byte $A8, $85, $00
    .byte $AC, $8D, $00
    .byte $A8, $9D, $00
    .byte $E4, $93, $00
    .byte $B0, $8D, $00
    .byte $F0, $83, $00
    .byte $E0, $83, $00
    .byte $C8, $92, $00
    .byte $C6, $B2, $00
    .byte $CA, $D2, $00
    .byte $D0, $97, $00
    .byte $E0, $96, $00
    .byte $A8, $A8, $00
    .byte $94, $A8, $00
    .byte $88, $90, $00
    .byte $98, $B0, $00
    .byte $98, $F0, $00
    .byte $8E, $D0, $00
    .byte $8E, $00, $00
    .byte $8A, $D0, $00
; Shift 1
    .byte $D0, $8A, $00
    .byte $D8, $9A, $00
    .byte $D0, $BA, $00
    .byte $C8, $A7, $00
    .byte $E0, $9A, $00
    .byte $E0, $87, $00
    .byte $C0, $87, $00
    .byte $90, $A5, $00
    .byte $8C, $E5, $00
    .byte $94, $A5, $81
    .byte $A0, $AF, $00
    .byte $C0, $AD, $00
    .byte $D0, $D0, $00
    .byte $A8, $D0, $00
    .byte $90, $A0, $00
    .byte $B0, $E0, $00
    .byte $B0, $E0, $81
    .byte $9C, $A0, $81
    .byte $9C, $00, $00
    .byte $94, $A0, $81
; Shift 2
    .byte $A0, $95, $00
    .byte $B0, $B5, $00
    .byte $A0, $F5, $00
    .byte $90, $CF, $00
    .byte $C0, $B5, $00
    .byte $C0, $8F, $00
    .byte $00, $8F, $00
    .byte $A0, $CA, $00
    .byte $98, $CA, $81
    .byte $A8, $CA, $82
    .byte $C0, $DE, $00
    .byte $00, $DB, $00
    .byte $A0, $A1, $81
    .byte $D0, $A0, $81
    .byte $A0, $C0, $00
    .byte $E0, $C0, $81
    .byte $E0, $C0, $83
    .byte $B8, $C0, $82
    .byte $B8, $00, $00
    .byte $A8, $C0, $82
; Shift 3
    .byte $C0, $AA, $00
    .byte $E0, $EA, $00
    .byte $C0, $EA, $81
    .byte $A0, $9E, $81
    .byte $00, $EB, $00
    .byte $00, $9F, $00
    .byte $00, $9E, $00
    .byte $C0, $94, $81
    .byte $B0, $94, $83
    .byte $D0, $94, $85
    .byte $00, $BD, $81
    .byte $00, $B6, $81
    .byte $C0, $C2, $82
    .byte $A0, $C1, $82
    .byte $C0, $00, $81
    .byte $C0, $81, $83
    .byte $C0, $81, $87
    .byte $F0, $00, $85
    .byte $F0, $00, $00
    .byte $D0, $00, $85
; Shift 4
    .byte $00, $D5, $00
    .byte $C0, $D5, $81
    .byte $00, $D5, $83
    .byte $C0, $BC, $82
    .byte $00, $D6, $81
    .byte $00, $BE, $00
    .byte $00, $BC, $00
    .byte $00, $A9, $82
    .byte $E0, $A8, $86
    .byte $A0, $A9, $8A
    .byte $00, $FA, $82
    .byte $00, $EC, $82
    .byte $00, $85, $85
    .byte $C0, $82, $85
    .byte $00, $81, $82
    .byte $00, $83, $86
    .byte $00, $83, $8E
    .byte $E0, $81, $8A
    .byte $E0, $81, $00
    .byte $A0, $81, $8A
; Shift 5
    .byte $00, $AA, $81
    .byte $00, $AB, $83
    .byte $00, $AA, $87
    .byte $00, $F9, $84
    .byte $00, $AC, $83
    .byte $00, $FC, $00
    .byte $00, $F8, $00
    .byte $00, $D2, $84
    .byte $C0, $D1, $8C
    .byte $C0, $D2, $94
    .byte $00, $F4, $85
    .byte $00, $D8, $85
    .byte $00, $8A, $8A
    .byte $00, $85, $8A
    .byte $00, $82, $84
    .byte $00, $86, $8C
    .byte $00, $86, $9C
    .byte $C0, $83, $94
    .byte $C0, $83, $00
    .byte $C0, $82, $94
; Shift 6
    .byte $00, $D4, $82
    .byte $00, $D6, $86
    .byte $00, $D4, $8E
    .byte $00, $F2, $89
    .byte $00, $D8, $86
    .byte $00, $F8, $81
    .byte $00, $F0, $81
    .byte $00, $A4, $89
    .byte $00, $A3, $99
    .byte $00, $A5, $A9
    .byte $00, $E8, $8B
    .byte $00, $B0, $8B
    .byte $00, $94, $94
    .byte $00, $8A, $94
    .byte $00, $84, $88
    .byte $00, $8C, $98
    .byte $00, $8C, $B8
    .byte $00, $87, $A8
    .byte $00, $87, $00
    .byte $00, $85, $A8

; Sprite: spr_player_shoot (20 lines x 3 bytes x 7 shifts)
spr_player_shoot:
; Shift 0
    .byte $C0, $81, $00
    .byte $C0, $81, $00
    .byte $E0, $83, $00
    .byte $A8, $85, $00
    .byte $AC, $8D, $00
    .byte $98, $86, $00
    .byte $B0, $83, $00
    .byte $EC, $9B, $00
    .byte $CA, $A9, $00
    .byte $A4, $89, $00
    .byte $A4, $89, $00
    .byte $F4, $85, $00
    .byte $B4, $8B, $00
    .byte $8A, $8A, $00
    .byte $8A, $94, $00
    .byte $84, $88, $00
    .byte $86, $8C, $00
    .byte $8E, $9C, $00
    .byte $8F, $BC, $00
    .byte $85, $A8, $00
; Shift 1
    .byte $00, $83, $00
    .byte $00, $83, $00
    .byte $C0, $87, $00
    .byte $D0, $8A, $00
    .byte $D8, $9A, $00
    .byte $B0, $8C, $00
    .byte $E0, $86, $00
    .byte $D8, $B7, $00
    .byte $94, $D3, $00
    .byte $C8, $92, $00
    .byte $C8, $92, $00
    .byte $E8, $8B, $00
    .byte $E8, $96, $00
    .byte $94, $94, $00
    .byte $94, $A8, $00
    .byte $88, $90, $00
    .byte $8C, $98, $00
    .byte $9C, $B8, $00
    .byte $9E, $F8, $00
    .byte $8A, $D0, $00
; Shift 2
    .byte $00, $86, $00
    .byte $00, $86, $00
    .byte $00, $8F, $00
    .byte $A0, $95, $00
    .byte $B0, $B5, $00
    .byte $E0, $98, $00
    .byte $C0, $8D, $00
    .byte $B0, $EF, $00
    .byte $A8, $A6, $81
    .byte $90, $A5, $00
    .byte $90, $A5, $00
    .byte $D0, $97, $00
    .byte $D0, $AD, $00
    .byte $A8, $A8, $00
    .byte $A8, $D0, $00
    .byte $90, $A0, $00
    .byte $98, $B0, $00
    .byte $B8, $F0, $00
    .byte $BC, $F0, $81
    .byte $94, $A0, $81
; Shift 3
    .byte $00, $8C, $00
    .byte $00, $8C, $00
    .byte $00, $9E, $00
    .byte $C0, $AA, $00
    .byte $E0, $EA, $00
    .byte $C0, $B1, $00
    .byte $00, $9B, $00
    .byte $E0, $DE, $81
    .byte $D0, $CC, $82
    .byte $A0, $CA, $00
    .byte $A0, $CA, $00
    .byte $A0, $AF, $00
    .byte $A0, $DB, $00
    .byte $D0, $D0, $00
    .byte $D0, $A0, $81
    .byte $A0, $C0, $00
    .byte $B0, $E0, $00
    .byte $F0, $E0, $81
    .byte $F8, $E0, $83
    .byte $A8, $C0, $82
; Shift 4
    .byte $00, $98, $00
    .byte $00, $98, $00
    .byte $00, $BC, $00
    .byte $00, $D5, $00
    .byte $C0, $D5, $81
    .byte $00, $E3, $00
    .byte $00, $B6, $00
    .byte $C0, $BD, $83
    .byte $A0, $99, $85
    .byte $C0, $94, $81
    .byte $C0, $94, $81
    .byte $C0, $DE, $00
    .byte $C0, $B6, $81
    .byte $A0, $A1, $81
    .byte $A0, $C1, $82
    .byte $C0, $00, $81
    .byte $E0, $C0, $81
    .byte $E0, $C1, $83
    .byte $F0, $C1, $87
    .byte $D0, $00, $85
; Shift 5
    .byte $00, $B0, $00
    .byte $00, $B0, $00
    .byte $00, $F8, $00
    .byte $00, $AA, $81
    .byte $00, $AB, $83
    .byte $00, $C6, $81
    .byte $00, $EC, $00
    .byte $00, $FB, $86
    .byte $C0, $B2, $8A
    .byte $00, $A9, $82
    .byte $00, $A9, $82
    .byte $00, $BD, $81
    .byte $00, $ED, $82
    .byte $C0, $C2, $82
    .byte $C0, $82, $85
    .byte $00, $81, $82
    .byte $C0, $81, $83
    .byte $C0, $83, $87
    .byte $E0, $83, $8F
    .byte $A0, $81, $8A
; Shift 6
    .byte $00, $E0, $00
    .byte $00, $E0, $00
    .byte $00, $F0, $81
    .byte $00, $D4, $82
    .byte $00, $D6, $86
    .byte $00, $8C, $83
    .byte $00, $D8, $81
    .byte $00, $F6, $8D
    .byte $00, $E5, $94
    .byte $00, $D2, $84
    .byte $00, $D2, $84
    .byte $00, $FA, $82
    .byte $00, $DA, $85
    .byte $00, $85, $85
    .byte $00, $85, $8A
    .byte $00, $82, $84
    .byte $00, $83, $86
    .byte $00, $87, $8E
    .byte $C0, $87, $9E
    .byte $C0, $82, $94

; Sprite: spr_player_hit (20 lines x 3 bytes x 7 shifts)
spr_player_hit:
; Shift 0
    .byte $E2, $90, $00
    .byte $AC, $8D, $00
    .byte $A8, $87, $00
    .byte $F2, $93, $00
    .byte $94, $8A, $00
    .byte $88, $84, $00
    .byte $98, $86, $00
    .byte $90, $82, $00
    .byte $F3, $B3, $00
    .byte $A5, $A9, $00
    .byte $AC, $8D, $00
    .byte $F4, $85, $00
    .byte $B4, $8B, $00
    .byte $86, $98, $00
    .byte $83, $B0, $00
    .byte $85, $A8, $00
    .byte $86, $98, $00
    .byte $87, $B8, $00
    .byte $85, $A8, $00
    .byte $B6, $B6, $00
; Shift 1
    .byte $C4, $A1, $00
    .byte $D8, $9A, $00
    .byte $D0, $8E, $00
    .byte $E4, $A7, $00
    .byte $A8, $94, $00
    .byte $90, $88, $00
    .byte $B0, $8C, $00
    .byte $A0, $84, $00
    .byte $E6, $E7, $00
    .byte $CA, $D2, $00
    .byte $D8, $9A, $00
    .byte $E8, $8B, $00
    .byte $E8, $96, $00
    .byte $8C, $B0, $00
    .byte $86, $E0, $00
    .byte $8A, $D0, $00
    .byte $8C, $B0, $00
    .byte $8E, $F0, $00
    .byte $8A, $D0, $00
    .byte $EC, $EC, $00
; Shift 2
    .byte $88, $C3, $00
    .byte $B0, $B5, $00
    .byte $A0, $9D, $00
    .byte $C8, $CF, $00
    .byte $D0, $A8, $00
    .byte $A0, $90, $00
    .byte $E0, $98, $00
    .byte $C0, $88, $00
    .byte $CC, $CF, $81
    .byte $94, $A5, $81
    .byte $B0, $B5, $00
    .byte $D0, $97, $00
    .byte $D0, $AD, $00
    .byte $98, $E0, $00
    .byte $8C, $C0, $81
    .byte $94, $A0, $81
    .byte $98, $E0, $00
    .byte $9C, $E0, $81
    .byte $94, $A0, $81
    .byte $D8, $D9, $81
; Shift 3
    .byte $90, $86, $81
    .byte $E0, $EA, $00
    .byte $C0, $BA, $00
    .byte $90, $9F, $81
    .byte $A0, $D1, $00
    .byte $C0, $A0, $00
    .byte $C0, $B1, $00
    .byte $00, $91, $00
    .byte $98, $9F, $83
    .byte $A8, $CA, $82
    .byte $E0, $EA, $00
    .byte $A0, $AF, $00
    .byte $A0, $DB, $00
    .byte $B0, $C0, $81
    .byte $98, $00, $83
    .byte $A8, $C0, $82
    .byte $B0, $C0, $81
    .byte $B8, $C0, $83
    .byte $A8, $C0, $82
    .byte $B0, $B3, $83
; Shift 4
    .byte $A0, $8C, $82
    .byte $C0, $D5, $81
    .byte $00, $F5, $00
    .byte $A0, $BE, $82
    .byte $C0, $A2, $81
    .byte $00, $C1, $00
    .byte $00, $E3, $00
    .byte $00, $A2, $00
    .byte $B0, $BE, $86
    .byte $D0, $94, $85
    .byte $C0, $D5, $81
    .byte $C0, $DE, $00
    .byte $C0, $B6, $81
    .byte $E0, $00, $83
    .byte $B0, $00, $86
    .byte $D0, $00, $85
    .byte $E0, $00, $83
    .byte $F0, $00, $87
    .byte $D0, $00, $85
    .byte $E0, $E6, $86
; Shift 5
    .byte $C0, $98, $84
    .byte $00, $AB, $83
    .byte $00, $EA, $81
    .byte $C0, $FC, $84
    .byte $00, $C5, $82
    .byte $00, $82, $81
    .byte $00, $C6, $81
    .byte $00, $C4, $00
    .byte $E0, $FC, $8C
    .byte $A0, $A9, $8A
    .byte $00, $AB, $83
    .byte $00, $BD, $81
    .byte $00, $ED, $82
    .byte $C0, $81, $86
    .byte $E0, $00, $8C
    .byte $A0, $81, $8A
    .byte $C0, $81, $86
    .byte $E0, $81, $8E
    .byte $A0, $81, $8A
    .byte $C0, $CD, $8D
; Shift 6
    .byte $00, $B1, $88
    .byte $00, $D6, $86
    .byte $00, $D4, $83
    .byte $00, $F9, $89
    .byte $00, $8A, $85
    .byte $00, $84, $82
    .byte $00, $8C, $83
    .byte $00, $88, $81
    .byte $C0, $F9, $99
    .byte $C0, $D2, $94
    .byte $00, $D6, $86
    .byte $00, $FA, $82
    .byte $00, $DA, $85
    .byte $00, $83, $8C
    .byte $C0, $81, $98
    .byte $C0, $82, $94
    .byte $00, $83, $8C
    .byte $C0, $83, $9C
    .byte $C0, $82, $94
    .byte $00, $9B, $9B

; Sprite: spr_player_climb1 (20 lines x 3 bytes x 7 shifts)
spr_player_climb1:
; Shift 0
    .byte $A8, $85, $00
    .byte $AC, $8D, $00
    .byte $AC, $8D, $00
    .byte $F8, $87, $00
    .byte $D0, $82, $00
    .byte $D6, $82, $00
    .byte $92, $B2, $00
    .byte $D4, $8A, $00
    .byte $A8, $85, $00
    .byte $B0, $83, $00
    .byte $A8, $85, $00
    .byte $FC, $8F, $00
    .byte $D4, $8A, $00
    .byte $8C, $8C, $00
    .byte $84, $88, $00
    .byte $86, $84, $00
    .byte $87, $8C, $00
    .byte $85, $9C, $00
    .byte $00, $9E, $00
    .byte $00, $8A, $00
; Shift 1
    .byte $D0, $8A, $00
    .byte $D8, $9A, $00
    .byte $D8, $9A, $00
    .byte $F0, $8F, $00
    .byte $A0, $85, $00
    .byte $AC, $85, $00
    .byte $A4, $E4, $00
    .byte $A8, $95, $00
    .byte $D0, $8A, $00
    .byte $E0, $86, $00
    .byte $D0, $8A, $00
    .byte $F8, $9F, $00
    .byte $A8, $95, $00
    .byte $98, $98, $00
    .byte $88, $90, $00
    .byte $8C, $88, $00
    .byte $8E, $98, $00
    .byte $8A, $B8, $00
    .byte $00, $BC, $00
    .byte $00, $94, $00
; Shift 2
    .byte $A0, $95, $00
    .byte $B0, $B5, $00
    .byte $B0, $B5, $00
    .byte $E0, $9F, $00
    .byte $C0, $8A, $00
    .byte $D8, $8A, $00
    .byte $C8, $C8, $81
    .byte $D0, $AA, $00
    .byte $A0, $95, $00
    .byte $C0, $8D, $00
    .byte $A0, $95, $00
    .byte $F0, $BF, $00
    .byte $D0, $AA, $00
    .byte $B0, $B0, $00
    .byte $90, $A0, $00
    .byte $98, $90, $00
    .byte $9C, $B0, $00
    .byte $94, $F0, $00
    .byte $00, $F8, $00
    .byte $00, $A8, $00
; Shift 3
    .byte $C0, $AA, $00
    .byte $E0, $EA, $00
    .byte $E0, $EA, $00
    .byte $C0, $BF, $00
    .byte $00, $95, $00
    .byte $B0, $95, $00
    .byte $90, $91, $83
    .byte $A0, $D5, $00
    .byte $C0, $AA, $00
    .byte $00, $9B, $00
    .byte $C0, $AA, $00
    .byte $E0, $FF, $00
    .byte $A0, $D5, $00
    .byte $E0, $E0, $00
    .byte $A0, $C0, $00
    .byte $B0, $A0, $00
    .byte $B8, $E0, $00
    .byte $A8, $E0, $81
    .byte $00, $F0, $81
    .byte $00, $D0, $00
; Shift 4
    .byte $00, $D5, $00
    .byte $C0, $D5, $81
    .byte $C0, $D5, $81
    .byte $00, $FF, $00
    .byte $00, $AA, $00
    .byte $E0, $AA, $00
    .byte $A0, $A2, $86
    .byte $C0, $AA, $81
    .byte $00, $D5, $00
    .byte $00, $B6, $00
    .byte $00, $D5, $00
    .byte $C0, $FF, $81
    .byte $C0, $AA, $81
    .byte $C0, $C1, $81
    .byte $C0, $00, $81
    .byte $E0, $C0, $00
    .byte $F0, $C0, $81
    .byte $D0, $C0, $83
    .byte $00, $E0, $83
    .byte $00, $A0, $81
; Shift 5
    .byte $00, $AA, $81
    .byte $00, $AB, $83
    .byte $00, $AB, $83
    .byte $00, $FE, $81
    .byte $00, $D4, $00
    .byte $C0, $D5, $00
    .byte $C0, $C4, $8C
    .byte $00, $D5, $82
    .byte $00, $AA, $81
    .byte $00, $EC, $00
    .byte $00, $AA, $81
    .byte $00, $FF, $83
    .byte $00, $D5, $82
    .byte $00, $83, $83
    .byte $00, $81, $82
    .byte $C0, $81, $81
    .byte $E0, $81, $83
    .byte $A0, $81, $87
    .byte $00, $C0, $87
    .byte $00, $C0, $82
; Shift 6
    .byte $00, $D4, $82
    .byte $00, $D6, $86
    .byte $00, $D6, $86
    .byte $00, $FC, $83
    .byte $00, $A8, $81
    .byte $00, $AB, $81
    .byte $00, $89, $99
    .byte $00, $AA, $85
    .byte $00, $D4, $82
    .byte $00, $D8, $81
    .byte $00, $D4, $82
    .byte $00, $FE, $87
    .byte $00, $AA, $85
    .byte $00, $86, $86
    .byte $00, $82, $84
    .byte $00, $83, $82
    .byte $C0, $83, $86
    .byte $C0, $82, $8E
    .byte $00, $00, $8F
    .byte $00, $00, $85

; Sprite: spr_player_climb2 (20 lines x 3 bytes x 7 shifts)
spr_player_climb2:
; Shift 0
    .byte $A8, $85, $00
    .byte $AC, $8D, $00
    .byte $AC, $8D, $00
    .byte $F8, $87, $00
    .byte $D0, $82, $00
    .byte $D0, $B2, $00
    .byte $A6, $A4, $00
    .byte $A8, $95, $00
    .byte $A8, $85, $00
    .byte $B0, $83, $00
    .byte $A8, $85, $00
    .byte $FC, $8F, $00
    .byte $D4, $8A, $00
    .byte $8C, $8C, $00
    .byte $88, $90, $00
    .byte $90, $98, $00
    .byte $98, $B8, $00
    .byte $9C, $A8, $00
    .byte $9E, $00, $00
    .byte $8A, $00, $00
; Shift 1
    .byte $D0, $8A, $00
    .byte $D8, $9A, $00
    .byte $D8, $9A, $00
    .byte $F0, $8F, $00
    .byte $A0, $85, $00
    .byte $A0, $E5, $00
    .byte $CC, $C8, $00
    .byte $D0, $AA, $00
    .byte $D0, $8A, $00
    .byte $E0, $86, $00
    .byte $D0, $8A, $00
    .byte $F8, $9F, $00
    .byte $A8, $95, $00
    .byte $98, $98, $00
    .byte $90, $A0, $00
    .byte $A0, $B0, $00
    .byte $B0, $F0, $00
    .byte $B8, $D0, $00
    .byte $BC, $00, $00
    .byte $94, $00, $00
; Shift 2
    .byte $A0, $95, $00
    .byte $B0, $B5, $00
    .byte $B0, $B5, $00
    .byte $E0, $9F, $00
    .byte $C0, $8A, $00
    .byte $C0, $CA, $81
    .byte $98, $91, $81
    .byte $A0, $D5, $00
    .byte $A0, $95, $00
    .byte $C0, $8D, $00
    .byte $A0, $95, $00
    .byte $F0, $BF, $00
    .byte $D0, $AA, $00
    .byte $B0, $B0, $00
    .byte $A0, $C0, $00
    .byte $C0, $E0, $00
    .byte $E0, $E0, $81
    .byte $F0, $A0, $81
    .byte $F8, $00, $00
    .byte $A8, $00, $00
; Shift 3
    .byte $C0, $AA, $00
    .byte $E0, $EA, $00
    .byte $E0, $EA, $00
    .byte $C0, $BF, $00
    .byte $00, $95, $00
    .byte $00, $95, $83
    .byte $B0, $A2, $82
    .byte $C0, $AA, $81
    .byte $C0, $AA, $00
    .byte $00, $9B, $00
    .byte $C0, $AA, $00
    .byte $E0, $FF, $00
    .byte $A0, $D5, $00
    .byte $E0, $E0, $00
    .byte $C0, $00, $81
    .byte $00, $C1, $81
    .byte $C0, $C1, $83
    .byte $E0, $C1, $82
    .byte $F0, $81, $00
    .byte $D0, $00, $00
; Shift 4
    .byte $00, $D5, $00
    .byte $C0, $D5, $81
    .byte $C0, $D5, $81
    .byte $00, $FF, $00
    .byte $00, $AA, $00
    .byte $00, $AA, $86
    .byte $E0, $C4, $84
    .byte $00, $D5, $82
    .byte $00, $D5, $00
    .byte $00, $B6, $00
    .byte $00, $D5, $00
    .byte $C0, $FF, $81
    .byte $C0, $AA, $81
    .byte $C0, $C1, $81
    .byte $00, $81, $82
    .byte $00, $82, $83
    .byte $00, $83, $87
    .byte $C0, $83, $85
    .byte $E0, $83, $00
    .byte $A0, $81, $00
; Shift 5
    .byte $00, $AA, $81
    .byte $00, $AB, $83
    .byte $00, $AB, $83
    .byte $00, $FE, $81
    .byte $00, $D4, $00
    .byte $00, $D4, $8C
    .byte $C0, $89, $89
    .byte $00, $AA, $85
    .byte $00, $AA, $81
    .byte $00, $EC, $00
    .byte $00, $AA, $81
    .byte $00, $FF, $83
    .byte $00, $D5, $82
    .byte $00, $83, $83
    .byte $00, $82, $84
    .byte $00, $84, $86
    .byte $00, $86, $8E
    .byte $00, $87, $8A
    .byte $C0, $87, $00
    .byte $C0, $82, $00
; Shift 6
    .byte $00, $D4, $82
    .byte $00, $D6, $86
    .byte $00, $D6, $86
    .byte $00, $FC, $83
    .byte $00, $A8, $81
    .byte $00, $A8, $99
    .byte $00, $93, $92
    .byte $00, $D4, $8A
    .byte $00, $D4, $82
    .byte $00, $D8, $81
    .byte $00, $D4, $82
    .byte $00, $FE, $87
    .byte $00, $AA, $85
    .byte $00, $86, $86
    .byte $00, $84, $88
    .byte $00, $88, $8C
    .byte $00, $8C, $9C
    .byte $00, $8E, $94
    .byte $00, $8F, $00
    .byte $00, $85, $00

; ===================================================================
; TILE GRAPHICS (1 BYTE x 8 SCANLINES)
; ===================================================================
tile_solid_gfx:
    .byte $FF, $D5, $AA, $D5, $AA, $D5, $AA, $80

tile_breakable_gfx:
    .byte $FF, $D5, $BE, $BE, $BE, $D5, $FF, $80

tile_ladder_gfx:
    .byte $A2, $BE, $A2, $A2, $BE, $A2, $A2, $BE

; Sprite: spr_harpoon_tip (8 lines x 2 bytes x 7 shifts)
spr_harpoon_tip:
; Shift 0
    .byte $08, $00
    .byte $1C, $00
    .byte $3E, $00
    .byte $7F, $00
    .byte $6B, $00
    .byte $49, $00
    .byte $08, $00
    .byte $08, $00
; Shift 1
    .byte $10, $00
    .byte $38, $00
    .byte $7C, $00
    .byte $7E, $01
    .byte $56, $01
    .byte $12, $01
    .byte $10, $00
    .byte $10, $00
; Shift 2
    .byte $20, $00
    .byte $70, $00
    .byte $78, $01
    .byte $7C, $03
    .byte $2C, $03
    .byte $24, $02
    .byte $20, $00
    .byte $20, $00
; Shift 3
    .byte $40, $00
    .byte $60, $01
    .byte $70, $03
    .byte $78, $07
    .byte $58, $06
    .byte $48, $04
    .byte $40, $00
    .byte $40, $00
; Shift 4
    .byte $00, $01
    .byte $40, $03
    .byte $60, $07
    .byte $70, $0F
    .byte $30, $0D
    .byte $10, $09
    .byte $00, $01
    .byte $00, $01
; Shift 5
    .byte $00, $02
    .byte $00, $07
    .byte $40, $0F
    .byte $60, $1F
    .byte $60, $1A
    .byte $20, $12
    .byte $00, $02
    .byte $00, $02
; Shift 6
    .byte $00, $04
    .byte $00, $0E
    .byte $00, $1F
    .byte $40, $3F
    .byte $40, $35
    .byte $40, $24
    .byte $00, $04
    .byte $00, $04

; Sprite: spr_pop_splash (8 lines x 2 bytes x 7 shifts)
spr_pop_splash:
; Shift 0
    .byte $99, $81
    .byte $DA, $00
    .byte $BC, $00
    .byte $FF, $81
    .byte $FF, $81
    .byte $BC, $00
    .byte $DA, $00
    .byte $99, $81
; Shift 1
    .byte $B2, $82
    .byte $B4, $81
    .byte $F8, $00
    .byte $FE, $83
    .byte $FE, $83
    .byte $F8, $00
    .byte $B4, $81
    .byte $B2, $82
; Shift 2
    .byte $E4, $84
    .byte $E8, $82
    .byte $F0, $81
    .byte $FC, $87
    .byte $FC, $87
    .byte $F0, $81
    .byte $E8, $82
    .byte $E4, $84
; Shift 3
    .byte $C8, $89
    .byte $D0, $85
    .byte $E0, $83
    .byte $F8, $8F
    .byte $F8, $8F
    .byte $E0, $83
    .byte $D0, $85
    .byte $C8, $89
; Shift 4
    .byte $90, $93
    .byte $A0, $8B
    .byte $C0, $87
    .byte $F0, $9F
    .byte $F0, $9F
    .byte $C0, $87
    .byte $A0, $8B
    .byte $90, $93
; Shift 5
    .byte $A0, $A6
    .byte $C0, $96
    .byte $00, $8F
    .byte $E0, $BF
    .byte $E0, $BF
    .byte $00, $8F
    .byte $C0, $96
    .byte $A0, $A6
; Shift 6
    .byte $C0, $CC
    .byte $00, $AD
    .byte $00, $9E
    .byte $C0, $FF
    .byte $C0, $FF
    .byte $00, $9E
    .byte $00, $AD
    .byte $C0, $CC

; Sprite: spr_ball_size0 (8 lines x 2 bytes x 7 shifts)
spr_ball_size0:
; Shift 0
    .byte $BC, $00
    .byte $E6, $00
    .byte $D7, $81
    .byte $A1, $81
    .byte $D5, $81
    .byte $EB, $81
    .byte $F6, $00
    .byte $BC, $00
; Shift 1
    .byte $F8, $00
    .byte $CC, $81
    .byte $AE, $83
    .byte $C2, $82
    .byte $AA, $83
    .byte $D6, $83
    .byte $EC, $81
    .byte $F8, $00
; Shift 2
    .byte $F0, $81
    .byte $98, $83
    .byte $DC, $86
    .byte $84, $85
    .byte $D4, $86
    .byte $AC, $87
    .byte $D8, $83
    .byte $F0, $81
; Shift 3
    .byte $E0, $83
    .byte $B0, $86
    .byte $B8, $8D
    .byte $88, $8A
    .byte $A8, $8D
    .byte $D8, $8E
    .byte $B0, $87
    .byte $E0, $83
; Shift 4
    .byte $C0, $87
    .byte $E0, $8C
    .byte $F0, $9A
    .byte $90, $94
    .byte $D0, $9A
    .byte $B0, $9D
    .byte $E0, $8E
    .byte $C0, $87
; Shift 5
    .byte $00, $8F
    .byte $C0, $99
    .byte $E0, $B5
    .byte $A0, $A8
    .byte $A0, $B5
    .byte $E0, $BA
    .byte $C0, $9D
    .byte $00, $8F
; Shift 6
    .byte $00, $9E
    .byte $00, $B3
    .byte $C0, $EB
    .byte $C0, $D0
    .byte $C0, $EA
    .byte $C0, $F5
    .byte $00, $BB
    .byte $00, $9E

; Sprite: spr_ball_size1 (14 lines x 3 bytes x 7 shifts)
spr_ball_size1:
; Shift 0
    .byte $F0, $87, $00
    .byte $98, $8D, $00
    .byte $DC, $9A, $00
    .byte $9E, $B5, $00
    .byte $DF, $EA, $00
    .byte $81, $D5, $00
    .byte $D5, $EA, $00
    .byte $AB, $D5, $00
    .byte $D5, $EA, $00
    .byte $AB, $F5, $00
    .byte $D6, $AA, $00
    .byte $AC, $95, $00
    .byte $D8, $8E, $00
    .byte $F0, $87, $00
; Shift 1
    .byte $E0, $8F, $00
    .byte $B0, $9A, $00
    .byte $B8, $B5, $00
    .byte $BC, $EA, $00
    .byte $BE, $D5, $81
    .byte $82, $AA, $81
    .byte $AA, $D5, $81
    .byte $D6, $AA, $81
    .byte $AA, $D5, $81
    .byte $D6, $EA, $81
    .byte $AC, $D5, $00
    .byte $D8, $AA, $00
    .byte $B0, $9D, $00
    .byte $E0, $8F, $00
; Shift 2
    .byte $C0, $9F, $00
    .byte $E0, $B4, $00
    .byte $F0, $EA, $00
    .byte $F8, $D4, $81
    .byte $FC, $AA, $83
    .byte $84, $D4, $82
    .byte $D4, $AA, $83
    .byte $AC, $D5, $82
    .byte $D4, $AA, $83
    .byte $AC, $D5, $83
    .byte $D8, $AA, $81
    .byte $B0, $D5, $00
    .byte $E0, $BA, $00
    .byte $C0, $9F, $00
; Shift 3
    .byte $00, $BF, $00
    .byte $C0, $E9, $00
    .byte $E0, $D5, $81
    .byte $F0, $A9, $83
    .byte $F8, $D5, $86
    .byte $88, $A8, $85
    .byte $A8, $D5, $86
    .byte $D8, $AA, $85
    .byte $A8, $D5, $86
    .byte $D8, $AA, $87
    .byte $B0, $D5, $82
    .byte $E0, $AA, $81
    .byte $C0, $F5, $00
    .byte $00, $BF, $00
; Shift 4
    .byte $00, $FE, $00
    .byte $00, $D3, $81
    .byte $C0, $AB, $83
    .byte $E0, $D3, $86
    .byte $F0, $AB, $8D
    .byte $90, $D0, $8A
    .byte $D0, $AA, $8D
    .byte $B0, $D5, $8A
    .byte $D0, $AA, $8D
    .byte $B0, $D5, $8E
    .byte $E0, $AA, $85
    .byte $C0, $D5, $82
    .byte $00, $EB, $81
    .byte $00, $FE, $00
; Shift 5
    .byte $00, $FC, $81
    .byte $00, $A6, $83
    .byte $00, $D7, $86
    .byte $C0, $A7, $8D
    .byte $E0, $D7, $9A
    .byte $A0, $A0, $95
    .byte $A0, $D5, $9A
    .byte $E0, $AA, $95
    .byte $A0, $D5, $9A
    .byte $E0, $AA, $9D
    .byte $C0, $D5, $8A
    .byte $00, $AB, $85
    .byte $00, $D6, $83
    .byte $00, $FC, $81
; Shift 6
    .byte $00, $F8, $83
    .byte $00, $CC, $86
    .byte $00, $AE, $8D
    .byte $00, $CF, $9A
    .byte $C0, $AF, $B5
    .byte $C0, $C0, $AA
    .byte $C0, $AA, $B5
    .byte $C0, $D5, $AA
    .byte $C0, $AA, $B5
    .byte $C0, $D5, $BA
    .byte $00, $AB, $95
    .byte $00, $D6, $8A
    .byte $00, $AC, $87
    .byte $00, $F8, $83

; Sprite: spr_ball_size2 (20 lines x 4 bytes x 7 shifts)
spr_ball_size2:
; Shift 0
    .byte $00, $BF, $00, $00
    .byte $E0, $D5, $81, $00
    .byte $98, $AA, $87, $00
    .byte $FC, $D4, $8E, $00
    .byte $FC, $A8, $8D, $00
    .byte $FA, $D4, $9A, $00
    .byte $FA, $A8, $95, $00
    .byte $83, $D4, $AA, $00
    .byte $85, $AA, $B5, $00
    .byte $AB, $D5, $AA, $00
    .byte $D5, $AA, $B5, $00
    .byte $AB, $D5, $AA, $00
    .byte $D5, $AA, $B5, $00
    .byte $AA, $D5, $9A, $00
    .byte $D6, $AA, $95, $00
    .byte $AC, $D5, $8A, $00
    .byte $DC, $AA, $8D, $00
    .byte $B8, $D5, $86, $00
    .byte $E0, $EA, $81, $00
    .byte $00, $BF, $00, $00
; Shift 1
    .byte $00, $FE, $00, $00
    .byte $C0, $AB, $83, $00
    .byte $B0, $D4, $8E, $00
    .byte $F8, $A9, $9D, $00
    .byte $F8, $D1, $9A, $00
    .byte $F4, $A9, $B5, $00
    .byte $F4, $D1, $AA, $00
    .byte $86, $A8, $D5, $00
    .byte $8A, $D4, $EA, $00
    .byte $D6, $AA, $D5, $00
    .byte $AA, $D5, $EA, $00
    .byte $D6, $AA, $D5, $00
    .byte $AA, $D5, $EA, $00
    .byte $D4, $AA, $B5, $00
    .byte $AC, $D5, $AA, $00
    .byte $D8, $AA, $95, $00
    .byte $B8, $D5, $9A, $00
    .byte $F0, $AA, $8D, $00
    .byte $C0, $D5, $83, $00
    .byte $00, $FE, $00, $00
; Shift 2
    .byte $00, $FC, $81, $00
    .byte $00, $D7, $86, $00
    .byte $E0, $A8, $9D, $00
    .byte $F0, $D3, $BA, $00
    .byte $F0, $A3, $B5, $00
    .byte $E8, $D3, $EA, $00
    .byte $E8, $A3, $D5, $00
    .byte $8C, $D0, $AA, $81
    .byte $94, $A8, $D5, $81
    .byte $AC, $D5, $AA, $81
    .byte $D4, $AA, $D5, $81
    .byte $AC, $D5, $AA, $81
    .byte $D4, $AA, $D5, $81
    .byte $A8, $D5, $EA, $00
    .byte $D8, $AA, $D5, $00
    .byte $B0, $D5, $AA, $00
    .byte $F0, $AA, $B5, $00
    .byte $E0, $D5, $9A, $00
    .byte $00, $AB, $87, $00
    .byte $00, $FC, $81, $00
; Shift 3
    .byte $00, $F8, $83, $00
    .byte $00, $AE, $8D, $00
    .byte $C0, $D1, $BA, $00
    .byte $E0, $A7, $F5, $00
    .byte $E0, $C7, $EA, $00
    .byte $D0, $A7, $D5, $81
    .byte $D0, $C7, $AA, $81
    .byte $98, $A0, $D5, $82
    .byte $A8, $D0, $AA, $83
    .byte $D8, $AA, $D5, $82
    .byte $A8, $D5, $AA, $83
    .byte $D8, $AA, $D5, $82
    .byte $A8, $D5, $AA, $83
    .byte $D0, $AA, $D5, $81
    .byte $B0, $D5, $AA, $81
    .byte $E0, $AA, $D5, $00
    .byte $E0, $D5, $EA, $00
    .byte $C0, $AB, $B5, $00
    .byte $00, $D6, $8E, $00
    .byte $00, $F8, $83, $00
; Shift 4
    .byte $00, $F0, $87, $00
    .byte $00, $DC, $9A, $00
    .byte $00, $A3, $F5, $00
    .byte $C0, $CF, $EA, $81
    .byte $C0, $8F, $D5, $81
    .byte $A0, $CF, $AA, $83
    .byte $A0, $8F, $D5, $82
    .byte $B0, $C0, $AA, $85
    .byte $D0, $A0, $D5, $86
    .byte $B0, $D5, $AA, $85
    .byte $D0, $AA, $D5, $86
    .byte $B0, $D5, $AA, $85
    .byte $D0, $AA, $D5, $86
    .byte $A0, $D5, $AA, $83
    .byte $E0, $AA, $D5, $82
    .byte $C0, $D5, $AA, $81
    .byte $C0, $AB, $D5, $81
    .byte $00, $D7, $EA, $00
    .byte $00, $AC, $9D, $00
    .byte $00, $F0, $87, $00
; Shift 5
    .byte $00, $E0, $8F, $00
    .byte $00, $B8, $B5, $00
    .byte $00, $C6, $EA, $81
    .byte $00, $9F, $D5, $83
    .byte $00, $9F, $AA, $83
    .byte $C0, $9E, $D5, $86
    .byte $C0, $9E, $AA, $85
    .byte $E0, $00, $D5, $8A
    .byte $A0, $C1, $AA, $8D
    .byte $E0, $AA, $D5, $8A
    .byte $A0, $D5, $AA, $8D
    .byte $E0, $AA, $D5, $8A
    .byte $A0, $D5, $AA, $8D
    .byte $C0, $AA, $D5, $86
    .byte $C0, $D5, $AA, $85
    .byte $00, $AB, $D5, $82
    .byte $00, $D7, $AA, $83
    .byte $00, $AE, $D5, $81
    .byte $00, $D8, $BA, $00
    .byte $00, $E0, $8F, $00
; Shift 6
    .byte $00, $C0, $9F, $00
    .byte $00, $F0, $EA, $00
    .byte $00, $8C, $D5, $83
    .byte $00, $BE, $AA, $87
    .byte $00, $BE, $D4, $86
    .byte $00, $BD, $AA, $8D
    .byte $00, $BD, $D4, $8A
    .byte $C0, $81, $AA, $95
    .byte $C0, $82, $D5, $9A
    .byte $C0, $D5, $AA, $95
    .byte $C0, $AA, $D5, $9A
    .byte $C0, $D5, $AA, $95
    .byte $C0, $AA, $D5, $9A
    .byte $00, $D5, $AA, $8D
    .byte $00, $AB, $D5, $8A
    .byte $00, $D6, $AA, $85
    .byte $00, $AE, $D5, $86
    .byte $00, $DC, $AA, $83
    .byte $00, $B0, $F5, $00
    .byte $00, $C0, $9F, $00

; Sprite: spr_ball_size3 (26 lines x 5 bytes x 7 shifts)
spr_ball_size3:
; Shift 0
    .byte $00, $FC, $87, $00, $00
    .byte $00, $D7, $9E, $00, $00
    .byte $E0, $A8, $F5, $00, $00
    .byte $F0, $D1, $EA, $81, $00
    .byte $F8, $A3, $D5, $83, $00
    .byte $FC, $C3, $AA, $87, $00
    .byte $FC, $A7, $D5, $86, $00
    .byte $FA, $C3, $AA, $8D, $00
    .byte $F2, $A3, $D5, $8A, $00
    .byte $C3, $D0, $AA, $9D, $00
    .byte $85, $A8, $D5, $9A, $00
    .byte $8B, $D4, $AA, $95, $00
    .byte $D5, $AA, $D5, $9A, $00
    .byte $AB, $D5, $AA, $95, $00
    .byte $D5, $AA, $D5, $9A, $00
    .byte $AB, $D5, $AA, $95, $00
    .byte $D7, $AA, $D5, $9A, $00
    .byte $AA, $D5, $AA, $8D, $00
    .byte $D6, $AA, $D5, $8A, $00
    .byte $AC, $D5, $AA, $85, $00
    .byte $DC, $AA, $D5, $86, $00
    .byte $B8, $D5, $AA, $83, $00
    .byte $F0, $AA, $D5, $81, $00
    .byte $E0, $D5, $EA, $00, $00
    .byte $00, $AF, $9D, $00, $00
    .byte $00, $FC, $87, $00, $00
; Shift 1
    .byte $00, $F8, $8F, $00, $00
    .byte $00, $AE, $BD, $00, $00
    .byte $C0, $D1, $EA, $81, $00
    .byte $E0, $A3, $D5, $83, $00
    .byte $F0, $C7, $AA, $87, $00
    .byte $F8, $87, $D5, $8E, $00
    .byte $F8, $CF, $AA, $8D, $00
    .byte $F4, $87, $D5, $9A, $00
    .byte $E4, $C7, $AA, $95, $00
    .byte $86, $A1, $D5, $BA, $00
    .byte $8A, $D0, $AA, $B5, $00
    .byte $96, $A8, $D5, $AA, $00
    .byte $AA, $D5, $AA, $B5, $00
    .byte $D6, $AA, $D5, $AA, $00
    .byte $AA, $D5, $AA, $B5, $00
    .byte $D6, $AA, $D5, $AA, $00
    .byte $AE, $D5, $AA, $B5, $00
    .byte $D4, $AA, $D5, $9A, $00
    .byte $AC, $D5, $AA, $95, $00
    .byte $D8, $AA, $D5, $8A, $00
    .byte $B8, $D5, $AA, $8D, $00
    .byte $F0, $AA, $D5, $86, $00
    .byte $E0, $D5, $AA, $83, $00
    .byte $C0, $AB, $D5, $81, $00
    .byte $00, $DE, $BA, $00, $00
    .byte $00, $F8, $8F, $00, $00
; Shift 2
    .byte $00, $F0, $9F, $00, $00
    .byte $00, $DC, $FA, $00, $00
    .byte $00, $A3, $D5, $83, $00
    .byte $C0, $C7, $AA, $87, $00
    .byte $E0, $8F, $D5, $8E, $00
    .byte $F0, $8F, $AA, $9D, $00
    .byte $F0, $9F, $D5, $9A, $00
    .byte $E8, $8F, $AA, $B5, $00
    .byte $C8, $8F, $D5, $AA, $00
    .byte $8C, $C2, $AA, $F5, $00
    .byte $94, $A0, $D5, $EA, $00
    .byte $AC, $D0, $AA, $D5, $00
    .byte $D4, $AA, $D5, $EA, $00
    .byte $AC, $D5, $AA, $D5, $00
    .byte $D4, $AA, $D5, $EA, $00
    .byte $AC, $D5, $AA, $D5, $00
    .byte $DC, $AA, $D5, $EA, $00
    .byte $A8, $D5, $AA, $B5, $00
    .byte $D8, $AA, $D5, $AA, $00
    .byte $B0, $D5, $AA, $95, $00
    .byte $F0, $AA, $D5, $9A, $00
    .byte $E0, $D5, $AA, $8D, $00
    .byte $C0, $AB, $D5, $86, $00
    .byte $00, $D7, $AA, $83, $00
    .byte $00, $BC, $F5, $00, $00
    .byte $00, $F0, $9F, $00, $00
; Shift 3
    .byte $00, $E0, $BF, $00, $00
    .byte $00, $B8, $F5, $81, $00
    .byte $00, $C6, $AA, $87, $00
    .byte $00, $8F, $D5, $8E, $00
    .byte $C0, $9F, $AA, $9D, $00
    .byte $E0, $9F, $D4, $BA, $00
    .byte $E0, $BF, $AA, $B5, $00
    .byte $D0, $9F, $D4, $EA, $00
    .byte $90, $9F, $AA, $D5, $00
    .byte $98, $84, $D5, $EA, $81
    .byte $A8, $C0, $AA, $D5, $81
    .byte $D8, $A0, $D5, $AA, $81
    .byte $A8, $D5, $AA, $D5, $81
    .byte $D8, $AA, $D5, $AA, $81
    .byte $A8, $D5, $AA, $D5, $81
    .byte $D8, $AA, $D5, $AA, $81
    .byte $B8, $D5, $AA, $D5, $81
    .byte $D0, $AA, $D5, $EA, $00
    .byte $B0, $D5, $AA, $D5, $00
    .byte $E0, $AA, $D5, $AA, $00
    .byte $E0, $D5, $AA, $B5, $00
    .byte $C0, $AB, $D5, $9A, $00
    .byte $00, $D7, $AA, $8D, $00
    .byte $00, $AE, $D5, $86, $00
    .byte $00, $F8, $EA, $81, $00
    .byte $00, $E0, $BF, $00, $00
; Shift 4
    .byte $00, $C0, $FF, $00, $00
    .byte $00, $F0, $EA, $83, $00
    .byte $00, $8C, $D5, $8E, $00
    .byte $00, $9E, $AA, $9D, $00
    .byte $00, $BF, $D4, $BA, $00
    .byte $C0, $BF, $A8, $F5, $00
    .byte $C0, $FF, $D4, $EA, $00
    .byte $A0, $BF, $A8, $D5, $81
    .byte $A0, $BE, $D4, $AA, $81
    .byte $B0, $88, $AA, $D5, $83
    .byte $D0, $00, $D5, $AA, $83
    .byte $B0, $C1, $AA, $D5, $82
    .byte $D0, $AA, $D5, $AA, $83
    .byte $B0, $D5, $AA, $D5, $82
    .byte $D0, $AA, $D5, $AA, $83
    .byte $B0, $D5, $AA, $D5, $82
    .byte $F0, $AA, $D5, $AA, $83
    .byte $A0, $D5, $AA, $D5, $81
    .byte $E0, $AA, $D5, $AA, $81
    .byte $C0, $D5, $AA, $D5, $00
    .byte $C0, $AB, $D5, $EA, $00
    .byte $00, $D7, $AA, $B5, $00
    .byte $00, $AE, $D5, $9A, $00
    .byte $00, $DC, $AA, $8D, $00
    .byte $00, $F0, $D5, $83, $00
    .byte $00, $C0, $FF, $00, $00
; Shift 5
    .byte $00, $00, $FF, $81, $00
    .byte $00, $E0, $D5, $87, $00
    .byte $00, $98, $AA, $9D, $00
    .byte $00, $BC, $D4, $BA, $00
    .byte $00, $FE, $A8, $F5, $00
    .byte $00, $FF, $D0, $EA, $81
    .byte $00, $FF, $A9, $D5, $81
    .byte $C0, $FE, $D0, $AA, $83
    .byte $C0, $FC, $A8, $D5, $82
    .byte $E0, $90, $D4, $AA, $87
    .byte $A0, $81, $AA, $D5, $86
    .byte $E0, $82, $D5, $AA, $85
    .byte $A0, $D5, $AA, $D5, $86
    .byte $E0, $AA, $D5, $AA, $85
    .byte $A0, $D5, $AA, $D5, $86
    .byte $E0, $AA, $D5, $AA, $85
    .byte $E0, $D5, $AA, $D5, $86
    .byte $C0, $AA, $D5, $AA, $83
    .byte $C0, $D5, $AA, $D5, $82
    .byte $00, $AB, $D5, $AA, $81
    .byte $00, $D7, $AA, $D5, $81
    .byte $00, $AE, $D5, $EA, $00
    .byte $00, $DC, $AA, $B5, $00
    .byte $00, $B8, $D5, $9A, $00
    .byte $00, $E0, $AB, $87, $00
    .byte $00, $00, $FF, $81, $00
; Shift 6
    .byte $00, $00, $FE, $83, $00
    .byte $00, $C0, $AB, $8F, $00
    .byte $00, $B0, $D4, $BA, $00
    .byte $00, $F8, $A8, $F5, $00
    .byte $00, $FC, $D1, $EA, $81
    .byte $00, $FE, $A1, $D5, $83
    .byte $00, $FE, $D3, $AA, $83
    .byte $00, $FD, $A1, $D5, $86
    .byte $00, $F9, $D1, $AA, $85
    .byte $C0, $A1, $A8, $D5, $8E
    .byte $C0, $82, $D4, $AA, $8D
    .byte $C0, $85, $AA, $D5, $8A
    .byte $C0, $AA, $D5, $AA, $8D
    .byte $C0, $D5, $AA, $D5, $8A
    .byte $C0, $AA, $D5, $AA, $8D
    .byte $C0, $D5, $AA, $D5, $8A
    .byte $C0, $AB, $D5, $AA, $8D
    .byte $00, $D5, $AA, $D5, $86
    .byte $00, $AB, $D5, $AA, $85
    .byte $00, $D6, $AA, $D5, $82
    .byte $00, $AE, $D5, $AA, $83
    .byte $00, $DC, $AA, $D5, $81
    .byte $00, $B8, $D5, $EA, $00
    .byte $00, $F0, $AA, $B5, $00
    .byte $00, $C0, $D7, $8E, $00
    .byte $00, $00, $FE, $83, $00

; ===================================================================
; CONTIGUOUS 8x8 FONT TABLE (ASCII 32 ' ' TO 90 'Z')
; Exact 8 bytes per character, 100% contiguous
; ===================================================================
font_base_32:
; Char ' ' (ASCII 32)
    .byte $00, $00, $00, $00, $00, $00, $00, $00
; Char '!' (ASCII 33)
    .byte $18, $18, $18, $18, $18, $00, $18, $00
; Char '"' (ASCII 34)
    .byte $66, $66, $66, $00, $00, $00, $00, $00
; Char '#' (ASCII 35)
    .byte $66, $7F, $66, $66, $7F, $66, $66, $00
; Char '$' (ASCII 36)
    .byte $18, $3C, $4D, $3C, $58, $3C, $18, $00
; Char '%' (ASCII 37)
    .byte $63, $33, $18, $0C, $46, $43, $00, $00
; Char '&' (ASCII 38)
    .byte $1E, $66, $66, $1E, $66, $73, $5E, $00
; Char ''' (ASCII 39)
    .byte $18, $18, $18, $00, $00, $00, $00, $00
; Char '(' (ASCII 40)
    .byte $30, $18, $0C, $0C, $0C, $18, $30, $00
; Char ')' (ASCII 41)
    .byte $0C, $18, $30, $30, $30, $18, $0C, $00
; Char '*' (ASCII 42)
    .byte $00, $66, $3C, $7F, $3C, $66, $00, $00
; Char '+' (ASCII 43)
    .byte $00, $18, $18, $7F, $18, $18, $00, $00
; Char ',' (ASCII 44)
    .byte $00, $00, $00, $00, $00, $18, $18, $0C
; Char '-' (ASCII 45)
    .byte $00, $00, $00, $7F, $00, $00, $00, $00
; Char '.' (ASCII 46)
    .byte $00, $00, $00, $00, $00, $18, $18, $00
; Char '/' (ASCII 47)
    .byte $40, $60, $30, $18, $0C, $06, $03, $00
; Char '0' (ASCII 48)
    .byte $7E, $43, $53, $5B, $4B, $43, $7E, $00
; Char '1' (ASCII 49)
    .byte $18, $1C, $18, $18, $18, $18, $3C, $00
; Char '2' (ASCII 50)
    .byte $7E, $43, $40, $7C, $03, $03, $7F, $00
; Char '3' (ASCII 51)
    .byte $7E, $43, $40, $78, $40, $43, $7E, $00
; Char '4' (ASCII 52)
    .byte $18, $1C, $36, $33, $7F, $30, $30, $00
; Char '5' (ASCII 53)
    .byte $7F, $03, $3F, $40, $40, $43, $7E, $00
; Char '6' (ASCII 54)
    .byte $7E, $43, $03, $3F, $43, $43, $7E, $00
; Char '7' (ASCII 55)
    .byte $7F, $40, $60, $30, $18, $18, $18, $00
; Char '8' (ASCII 56)
    .byte $7E, $43, $43, $7E, $43, $43, $7E, $00
; Char '9' (ASCII 57)
    .byte $7E, $43, $43, $7E, $40, $43, $7E, $00
; Char ':' (ASCII 58)
    .byte $00, $18, $18, $00, $18, $18, $00, $00
; Char ';' (ASCII 59)
    .byte $00, $18, $18, $00, $18, $18, $0C, $00
; Char '<' (ASCII 60)
    .byte $30, $18, $0C, $06, $0C, $18, $30, $00
; Char '=' (ASCII 61)
    .byte $00, $00, $7F, $00, $7F, $00, $00, $00
; Char '>' (ASCII 62)
    .byte $0C, $18, $30, $60, $30, $18, $0C, $00
; Char '?' (ASCII 63)
    .byte $7E, $43, $40, $78, $18, $00, $18, $00
; Char '@' (ASCII 64)
    .byte $7E, $43, $7B, $5B, $7B, $03, $7E, $00
; Char 'A' (ASCII 65)
    .byte $7E, $43, $43, $7F, $43, $43, $43, $00
; Char 'B' (ASCII 66)
    .byte $7F, $43, $43, $7F, $43, $43, $7F, $00
; Char 'C' (ASCII 67)
    .byte $7E, $43, $03, $03, $03, $43, $7E, $00
; Char 'D' (ASCII 68)
    .byte $3F, $63, $43, $43, $43, $63, $3F, $00
; Char 'E' (ASCII 69)
    .byte $7F, $03, $03, $3F, $03, $03, $7F, $00
; Char 'F' (ASCII 70)
    .byte $7F, $03, $03, $3F, $03, $03, $03, $00
; Char 'G' (ASCII 71)
    .byte $7E, $43, $03, $73, $43, $43, $7E, $00
; Char 'H' (ASCII 72)
    .byte $43, $43, $43, $7F, $43, $43, $43, $00
; Char 'I' (ASCII 73)
    .byte $7E, $18, $18, $18, $18, $18, $7E, $00
; Char 'J' (ASCII 74)
    .byte $70, $40, $40, $40, $43, $43, $7E, $00
; Char 'K' (ASCII 75)
    .byte $43, $63, $33, $1F, $33, $63, $43, $00
; Char 'L' (ASCII 76)
    .byte $03, $03, $03, $03, $03, $03, $7F, $00
; Char 'M' (ASCII 77)
    .byte $43, $67, $7F, $5B, $43, $43, $43, $00
; Char 'N' (ASCII 78)
    .byte $43, $47, $4F, $5B, $73, $63, $43, $00
; Char 'O' (ASCII 79)
    .byte $7E, $43, $43, $43, $43, $43, $7E, $00
; Char 'P' (ASCII 80)
    .byte $7F, $43, $43, $7F, $03, $03, $03, $00
; Char 'Q' (ASCII 81)
    .byte $7E, $43, $43, $43, $73, $43, $7E, $60
; Char 'R' (ASCII 82)
    .byte $7F, $43, $43, $7F, $33, $63, $43, $00
; Char 'S' (ASCII 83)
    .byte $7E, $43, $03, $7E, $40, $43, $7E, $00
; Char 'T' (ASCII 84)
    .byte $7F, $18, $18, $18, $18, $18, $18, $00
; Char 'U' (ASCII 85)
    .byte $43, $43, $43, $43, $43, $43, $7E, $00
; Char 'V' (ASCII 86)
    .byte $43, $43, $43, $43, $66, $66, $18, $00
; Char 'W' (ASCII 87)
    .byte $43, $43, $43, $5B, $7F, $67, $43, $00
; Char 'X' (ASCII 88)
    .byte $43, $66, $3C, $18, $3C, $66, $43, $00
; Char 'Y' (ASCII 89)
    .byte $43, $43, $66, $18, $18, $18, $18, $00
; Char 'Z' (ASCII 90)
    .byte $7F, $40, $60, $30, $18, $0C, $7F, $00

